{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.99.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.0.aar",
          "url": "nipworker-native-ffi-android-0.99.0.aar",
          "size": 34371466,
          "sha512": "914e6cebd3f98361950eab048c826ea0def2492123e25a9a934e7e991adad26c7f3b89fb86ed8749229f76dbe23f12aabeb8c76c27a45319b374e441921b6089",
          "sha256": "f38e6eb4ee11a80ee9d0b05c74c6a4e81e8003eea4f463031a6b6cb9e87ca3df",
          "sha1": "e35915f191b323c8190de872ad1884ed162d3784",
          "md5": "49637eed78d39cd77939e29dd0f63981"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.0.aar",
          "url": "nipworker-native-ffi-android-0.99.0.aar",
          "size": 34371466,
          "sha512": "914e6cebd3f98361950eab048c826ea0def2492123e25a9a934e7e991adad26c7f3b89fb86ed8749229f76dbe23f12aabeb8c76c27a45319b374e441921b6089",
          "sha256": "f38e6eb4ee11a80ee9d0b05c74c6a4e81e8003eea4f463031a6b6cb9e87ca3df",
          "sha1": "e35915f191b323c8190de872ad1884ed162d3784",
          "md5": "49637eed78d39cd77939e29dd0f63981"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.0-sources.jar",
          "url": "nipworker-native-ffi-android-0.99.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
