// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class ArticleBlockType {
  private ArticleBlockType() { }
  public static final byte Paragraph = 0;
  public static final byte Heading = 1;
  public static final byte Blockquote = 2;
  public static final byte List = 3;
  public static final byte ListItem = 4;
  public static final byte CodeBlock = 5;
  public static final byte Image = 6;
  public static final byte Video = 7;
  public static final byte ThematicBreak = 8;
  public static final byte Html = 9;

  public static final String[] names = { "Paragraph", "Heading", "Blockquote", "List", "ListItem", "CodeBlock", "Image", "Video", "ThematicBreak", "Html", };

  public static String name(int e) { return names[e]; }
}

