// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ArticleInline extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ArticleInline getRootAsArticleInline(ByteBuffer _bb) { return getRootAsArticleInline(_bb, new ArticleInline()); }
  public static ArticleInline getRootAsArticleInline(ByteBuffer _bb, ArticleInline obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ArticleInline __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String text() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer textInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String url() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String tag() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tagAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer tagInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public nostr.fb.ArticleEntity entity() { return entity(new nostr.fb.ArticleEntity()); }
  public nostr.fb.ArticleEntity entity(nostr.fb.ArticleEntity obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public nostr.fb.ArticleInline children(int j) { return children(new nostr.fb.ArticleInline(), j); }
  public nostr.fb.ArticleInline children(nostr.fb.ArticleInline obj, int j) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int childrenLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ArticleInline.Vector childrenVector() { return childrenVector(new nostr.fb.ArticleInline.Vector()); }
  public nostr.fb.ArticleInline.Vector childrenVector(nostr.fb.ArticleInline.Vector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createArticleInline(FlatBufferBuilder builder,
      byte type,
      int textOffset,
      int urlOffset,
      int tagOffset,
      int entityOffset,
      int childrenOffset) {
    builder.startTable(6);
    ArticleInline.addChildren(builder, childrenOffset);
    ArticleInline.addEntity(builder, entityOffset);
    ArticleInline.addTag(builder, tagOffset);
    ArticleInline.addUrl(builder, urlOffset);
    ArticleInline.addText(builder, textOffset);
    ArticleInline.addType(builder, type);
    return ArticleInline.endArticleInline(builder);
  }

  public static void startArticleInline(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addText(FlatBufferBuilder builder, int textOffset) { builder.addOffset(1, textOffset, 0); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(2, urlOffset, 0); }
  public static void addTag(FlatBufferBuilder builder, int tagOffset) { builder.addOffset(3, tagOffset, 0); }
  public static void addEntity(FlatBufferBuilder builder, int entityOffset) { builder.addOffset(4, entityOffset, 0); }
  public static void addChildren(FlatBufferBuilder builder, int childrenOffset) { builder.addOffset(5, childrenOffset, 0); }
  public static int createChildrenVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startChildrenVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endArticleInline(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ArticleInline get(int j) { return get(new ArticleInline(), j); }
    public ArticleInline get(ArticleInline obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

