// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ArticleBlock extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ArticleBlock getRootAsArticleBlock(ByteBuffer _bb) { return getRootAsArticleBlock(_bb, new ArticleBlock()); }
  public static ArticleBlock getRootAsArticleBlock(ByteBuffer _bb, ArticleBlock obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ArticleBlock __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String text() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer textInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String url() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String language() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer languageAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer languageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public int depth() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean ordered() { int o = __offset(14); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public long start() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public nostr.fb.ArticleInline inlines(int j) { return inlines(new nostr.fb.ArticleInline(), j); }
  public nostr.fb.ArticleInline inlines(nostr.fb.ArticleInline obj, int j) { int o = __offset(18); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int inlinesLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ArticleInline.Vector inlinesVector() { return inlinesVector(new nostr.fb.ArticleInline.Vector()); }
  public nostr.fb.ArticleInline.Vector inlinesVector(nostr.fb.ArticleInline.Vector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.ArticleBlock children(int j) { return children(new nostr.fb.ArticleBlock(), j); }
  public nostr.fb.ArticleBlock children(nostr.fb.ArticleBlock obj, int j) { int o = __offset(20); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int childrenLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ArticleBlock.Vector childrenVector() { return childrenVector(new nostr.fb.ArticleBlock.Vector()); }
  public nostr.fb.ArticleBlock.Vector childrenVector(nostr.fb.ArticleBlock.Vector obj) { int o = __offset(20); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createArticleBlock(FlatBufferBuilder builder,
      byte type,
      int textOffset,
      int urlOffset,
      int languageOffset,
      int depth,
      boolean ordered,
      long start,
      int inlinesOffset,
      int childrenOffset) {
    builder.startTable(9);
    ArticleBlock.addStart(builder, start);
    ArticleBlock.addChildren(builder, childrenOffset);
    ArticleBlock.addInlines(builder, inlinesOffset);
    ArticleBlock.addLanguage(builder, languageOffset);
    ArticleBlock.addUrl(builder, urlOffset);
    ArticleBlock.addText(builder, textOffset);
    ArticleBlock.addOrdered(builder, ordered);
    ArticleBlock.addDepth(builder, depth);
    ArticleBlock.addType(builder, type);
    return ArticleBlock.endArticleBlock(builder);
  }

  public static void startArticleBlock(FlatBufferBuilder builder) { builder.startTable(9); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addText(FlatBufferBuilder builder, int textOffset) { builder.addOffset(1, textOffset, 0); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(2, urlOffset, 0); }
  public static void addLanguage(FlatBufferBuilder builder, int languageOffset) { builder.addOffset(3, languageOffset, 0); }
  public static void addDepth(FlatBufferBuilder builder, int depth) { builder.addByte(4, (byte) depth, (byte) 0); }
  public static void addOrdered(FlatBufferBuilder builder, boolean ordered) { builder.addBoolean(5, ordered, false); }
  public static void addStart(FlatBufferBuilder builder, long start) { builder.addLong(6, start, 0L); }
  public static void addInlines(FlatBufferBuilder builder, int inlinesOffset) { builder.addOffset(7, inlinesOffset, 0); }
  public static int createInlinesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startInlinesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addChildren(FlatBufferBuilder builder, int childrenOffset) { builder.addOffset(8, childrenOffset, 0); }
  public static int createChildrenVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startChildrenVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endArticleBlock(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ArticleBlock get(int j) { return get(new ArticleBlock(), j); }
    public ArticleBlock get(ArticleBlock obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

