// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CacheRequest extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static CacheRequest getRootAsCacheRequest(ByteBuffer _bb) { return getRootAsCacheRequest(_bb, new CacheRequest()); }
  public static CacheRequest getRootAsCacheRequest(ByteBuffer _bb, CacheRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CacheRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String subId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer subIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer subIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public nostr.fb.Request requests(int j) { return requests(new nostr.fb.Request(), j); }
  public nostr.fb.Request requests(nostr.fb.Request obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int requestsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.Request.Vector requestsVector() { return requestsVector(new nostr.fb.Request.Vector()); }
  public nostr.fb.Request.Vector requestsVector(nostr.fb.Request.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.NostrEvent event() { return event(new nostr.fb.NostrEvent()); }
  public nostr.fb.NostrEvent event(nostr.fb.NostrEvent obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public nostr.fb.ParsedEvent parsedEvent() { return parsedEvent(new nostr.fb.ParsedEvent()); }
  public nostr.fb.ParsedEvent parsedEvent(nostr.fb.ParsedEvent obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String relays(int j) { int o = __offset(12); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int relaysLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public StringVector relaysVector() { return relaysVector(new StringVector()); }
  public StringVector relaysVector(StringVector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createCacheRequest(FlatBufferBuilder builder,
      int subIdOffset,
      int requestsOffset,
      int eventOffset,
      int parsedEventOffset,
      int relaysOffset) {
    builder.startTable(5);
    CacheRequest.addRelays(builder, relaysOffset);
    CacheRequest.addParsedEvent(builder, parsedEventOffset);
    CacheRequest.addEvent(builder, eventOffset);
    CacheRequest.addRequests(builder, requestsOffset);
    CacheRequest.addSubId(builder, subIdOffset);
    return CacheRequest.endCacheRequest(builder);
  }

  public static void startCacheRequest(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addSubId(FlatBufferBuilder builder, int subIdOffset) { builder.addOffset(0, subIdOffset, 0); }
  public static void addRequests(FlatBufferBuilder builder, int requestsOffset) { builder.addOffset(1, requestsOffset, 0); }
  public static int createRequestsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRequestsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addEvent(FlatBufferBuilder builder, int eventOffset) { builder.addOffset(2, eventOffset, 0); }
  public static void addParsedEvent(FlatBufferBuilder builder, int parsedEventOffset) { builder.addOffset(3, parsedEventOffset, 0); }
  public static void addRelays(FlatBufferBuilder builder, int relaysOffset) { builder.addOffset(4, relaysOffset, 0); }
  public static int createRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCacheRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // sub_id
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CacheRequest get(int j) { return get(new CacheRequest(), j); }
    public CacheRequest get(CacheRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

