// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class CacheInput {
  private CacheInput() { }
  public static final byte NONE = 0;
  public static final byte WorkerMessage = 1;
  public static final byte CacheRequest = 2;

  public static final String[] names = { "NONE", "WorkerMessage", "CacheRequest", };

  public static String name(int e) { return names[e]; }
}

