// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CacheResponse extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static CacheResponse getRootAsCacheResponse(ByteBuffer _bb) { return getRootAsCacheResponse(_bb, new CacheResponse()); }
  public static CacheResponse getRootAsCacheResponse(ByteBuffer _bb, CacheResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CacheResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String subId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer subIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer subIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int payload(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int payloadLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector payloadVector() { return payloadVector(new ByteVector()); }
  public ByteVector payloadVector(ByteVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer payloadAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer payloadInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createCacheResponse(FlatBufferBuilder builder,
      int subIdOffset,
      int payloadOffset) {
    builder.startTable(2);
    CacheResponse.addPayload(builder, payloadOffset);
    CacheResponse.addSubId(builder, subIdOffset);
    return CacheResponse.endCacheResponse(builder);
  }

  public static void startCacheResponse(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addSubId(FlatBufferBuilder builder, int subIdOffset) { builder.addOffset(0, subIdOffset, 0); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(1, payloadOffset, 0); }
  public static int createPayloadVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createPayloadVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startPayloadVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endCacheResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // sub_id
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CacheResponse get(int j) { return get(new CacheResponse(), j); }
    public CacheResponse get(CacheResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

