// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CashuData extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static CashuData getRootAsCashuData(ByteBuffer _bb) { return getRootAsCashuData(_bb, new CashuData()); }
  public static CashuData getRootAsCashuData(ByteBuffer _bb, CashuData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CashuData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String token() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tokenAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer tokenInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createCashuData(FlatBufferBuilder builder,
      int tokenOffset) {
    builder.startTable(1);
    CashuData.addToken(builder, tokenOffset);
    return CashuData.endCashuData(builder);
  }

  public static void startCashuData(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addToken(FlatBufferBuilder builder, int tokenOffset) { builder.addOffset(0, tokenOffset, 0); }
  public static int endCashuData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // token
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CashuData get(int j) { return get(new CashuData(), j); }
    public CashuData get(CashuData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

