// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ChatLimiterPipeConfig extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ChatLimiterPipeConfig getRootAsChatLimiterPipeConfig(ByteBuffer _bb) { return getRootAsChatLimiterPipeConfig(_bb, new ChatLimiterPipeConfig()); }
  public static ChatLimiterPipeConfig getRootAsChatLimiterPipeConfig(ByteBuffer _bb, ChatLimiterPipeConfig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ChatLimiterPipeConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String ownPubkey() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ownPubkeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer ownPubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long limitPerChat() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 5L; }
  public long maxChats() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 5000L; }
  public int kinds(int j) { int o = __offset(10); return o != 0 ? bb.getShort(__vector(o) + j * 2) & 0xFFFF : 0; }
  public int kindsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public ShortVector kindsVector() { return kindsVector(new ShortVector()); }
  public ShortVector kindsVector(ShortVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer kindsAsByteBuffer() { return __vector_as_bytebuffer(10, 2); }
  public ByteBuffer kindsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 2); }

  public static int createChatLimiterPipeConfig(FlatBufferBuilder builder,
      int ownPubkeyOffset,
      long limitPerChat,
      long maxChats,
      int kindsOffset) {
    builder.startTable(4);
    ChatLimiterPipeConfig.addKinds(builder, kindsOffset);
    ChatLimiterPipeConfig.addMaxChats(builder, maxChats);
    ChatLimiterPipeConfig.addLimitPerChat(builder, limitPerChat);
    ChatLimiterPipeConfig.addOwnPubkey(builder, ownPubkeyOffset);
    return ChatLimiterPipeConfig.endChatLimiterPipeConfig(builder);
  }

  public static void startChatLimiterPipeConfig(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addOwnPubkey(FlatBufferBuilder builder, int ownPubkeyOffset) { builder.addOffset(0, ownPubkeyOffset, 0); }
  public static void addLimitPerChat(FlatBufferBuilder builder, long limitPerChat) { builder.addInt(1, (int) limitPerChat, (int) 5L); }
  public static void addMaxChats(FlatBufferBuilder builder, long maxChats) { builder.addInt(2, (int) maxChats, (int) 5000L); }
  public static void addKinds(FlatBufferBuilder builder, int kindsOffset) { builder.addOffset(3, kindsOffset, 0); }
  public static int createKindsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort((short) data[i]); return builder.endVector(); }
  public static void startKindsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static int endChatLimiterPipeConfig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // own_pubkey
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ChatLimiterPipeConfig get(int j) { return get(new ChatLimiterPipeConfig(), j); }
    public ChatLimiterPipeConfig get(ChatLimiterPipeConfig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

