// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CodeData extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static CodeData getRootAsCodeData(ByteBuffer _bb) { return getRootAsCodeData(_bb, new CodeData()); }
  public static CodeData getRootAsCodeData(ByteBuffer _bb, CodeData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CodeData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String language() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer languageAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer languageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String code() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer codeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer codeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createCodeData(FlatBufferBuilder builder,
      int languageOffset,
      int codeOffset) {
    builder.startTable(2);
    CodeData.addCode(builder, codeOffset);
    CodeData.addLanguage(builder, languageOffset);
    return CodeData.endCodeData(builder);
  }

  public static void startCodeData(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addLanguage(FlatBufferBuilder builder, int languageOffset) { builder.addOffset(0, languageOffset, 0); }
  public static void addCode(FlatBufferBuilder builder, int codeOffset) { builder.addOffset(1, codeOffset, 0); }
  public static int endCodeData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // code
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CodeData get(int j) { return get(new CodeData(), j); }
    public CodeData get(CodeData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

