// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ConnectionStatus extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ConnectionStatus getRootAsConnectionStatus(ByteBuffer _bb) { return getRootAsConnectionStatus(_bb, new ConnectionStatus()); }
  public static ConnectionStatus getRootAsConnectionStatus(ByteBuffer _bb, ConnectionStatus obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ConnectionStatus __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String relayUrl() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer relayUrlAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer relayUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String status() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer statusAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer statusInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String message() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer messageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createConnectionStatus(FlatBufferBuilder builder,
      int relayUrlOffset,
      int statusOffset,
      int messageOffset) {
    builder.startTable(3);
    ConnectionStatus.addMessage(builder, messageOffset);
    ConnectionStatus.addStatus(builder, statusOffset);
    ConnectionStatus.addRelayUrl(builder, relayUrlOffset);
    return ConnectionStatus.endConnectionStatus(builder);
  }

  public static void startConnectionStatus(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addRelayUrl(FlatBufferBuilder builder, int relayUrlOffset) { builder.addOffset(0, relayUrlOffset, 0); }
  public static void addStatus(FlatBufferBuilder builder, int statusOffset) { builder.addOffset(1, statusOffset, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(2, messageOffset, 0); }
  public static int endConnectionStatus(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // relay_url
    builder.required(o, 6);  // status
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ConnectionStatus get(int j) { return get(new ConnectionStatus(), j); }
    public ConnectionStatus get(ConnectionStatus obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

