// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ContentBlock extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ContentBlock getRootAsContentBlock(ByteBuffer _bb) { return getRootAsContentBlock(_bb, new ContentBlock()); }
  public static ContentBlock getRootAsContentBlock(ByteBuffer _bb, ContentBlock obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ContentBlock __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String type() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer typeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer typeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String text() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer textInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public byte dataType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.google.flatbuffers.Table data(com.google.flatbuffers.Table obj) { int o = __offset(10); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createContentBlock(FlatBufferBuilder builder,
      int typeOffset,
      int textOffset,
      byte dataType,
      int dataOffset) {
    builder.startTable(4);
    ContentBlock.addData(builder, dataOffset);
    ContentBlock.addText(builder, textOffset);
    ContentBlock.addType(builder, typeOffset);
    ContentBlock.addDataType(builder, dataType);
    return ContentBlock.endContentBlock(builder);
  }

  public static void startContentBlock(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addType(FlatBufferBuilder builder, int typeOffset) { builder.addOffset(0, typeOffset, 0); }
  public static void addText(FlatBufferBuilder builder, int textOffset) { builder.addOffset(1, textOffset, 0); }
  public static void addDataType(FlatBufferBuilder builder, byte dataType) { builder.addByte(2, dataType, 0); }
  public static void addData(FlatBufferBuilder builder, int dataOffset) { builder.addOffset(3, dataOffset, 0); }
  public static int endContentBlock(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // type
    builder.required(o, 6);  // text
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ContentBlock get(int j) { return get(new ContentBlock(), j); }
    public ContentBlock get(ContentBlock obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

