// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Contact extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Contact getRootAsContact(ByteBuffer _bb) { return getRootAsContact(_bb, new Contact()); }
  public static Contact getRootAsContact(ByteBuffer _bb, Contact obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Contact __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String pubkey() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String relays(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int relaysLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public StringVector relaysVector() { return relaysVector(new StringVector()); }
  public StringVector relaysVector(StringVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String petname() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer petnameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer petnameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createContact(FlatBufferBuilder builder,
      int pubkeyOffset,
      int relaysOffset,
      int petnameOffset) {
    builder.startTable(3);
    Contact.addPetname(builder, petnameOffset);
    Contact.addRelays(builder, relaysOffset);
    Contact.addPubkey(builder, pubkeyOffset);
    return Contact.endContact(builder);
  }

  public static void startContact(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(0, pubkeyOffset, 0); }
  public static void addRelays(FlatBufferBuilder builder, int relaysOffset) { builder.addOffset(1, relaysOffset, 0); }
  public static int createRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addPetname(FlatBufferBuilder builder, int petnameOffset) { builder.addOffset(2, petnameOffset, 0); }
  public static int endContact(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // pubkey
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Contact get(int j) { return get(new Contact(), j); }
    public Contact get(Contact obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

