// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class ContentData {
  private ContentData() { }
  public static final byte NONE = 0;
  public static final byte CodeData = 1;
  public static final byte HashtagData = 2;
  public static final byte CashuData = 3;
  public static final byte ImageData = 4;
  public static final byte VideoData = 5;
  public static final byte MediaGroupData = 6;
  public static final byte NostrData = 7;
  public static final byte LinkPreviewData = 8;
  public static final byte EmojiData = 9;

  public static final String[] names = { "NONE", "CodeData", "HashtagData", "CashuData", "ImageData", "VideoData", "MediaGroupData", "NostrData", "LinkPreviewData", "EmojiData", };

  public static String name(int e) { return names[e]; }
}

