// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Coordinate extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Coordinate getRootAsCoordinate(ByteBuffer _bb) { return getRootAsCoordinate(_bb, new Coordinate()); }
  public static Coordinate getRootAsCoordinate(ByteBuffer _bb, Coordinate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Coordinate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long kind() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String pubkey() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String d() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer dInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String relays(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int relaysLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public StringVector relaysVector() { return relaysVector(new StringVector()); }
  public StringVector relaysVector(StringVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createCoordinate(FlatBufferBuilder builder,
      long kind,
      int pubkeyOffset,
      int dOffset,
      int relaysOffset) {
    builder.startTable(4);
    Coordinate.addKind(builder, kind);
    Coordinate.addRelays(builder, relaysOffset);
    Coordinate.addD(builder, dOffset);
    Coordinate.addPubkey(builder, pubkeyOffset);
    return Coordinate.endCoordinate(builder);
  }

  public static void startCoordinate(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addKind(FlatBufferBuilder builder, long kind) { builder.addLong(0, kind, 0L); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(1, pubkeyOffset, 0); }
  public static void addD(FlatBufferBuilder builder, int dOffset) { builder.addOffset(2, dOffset, 0); }
  public static void addRelays(FlatBufferBuilder builder, int relaysOffset) { builder.addOffset(3, relaysOffset, 0); }
  public static int createRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCoordinate(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // pubkey
    builder.required(o, 8);  // d
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Coordinate get(int j) { return get(new Coordinate(), j); }
    public Coordinate get(Coordinate obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

