// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CountResponse extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static CountResponse getRootAsCountResponse(ByteBuffer _bb) { return getRootAsCountResponse(_bb, new CountResponse()); }
  public static CountResponse getRootAsCountResponse(ByteBuffer _bb, CountResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CountResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long count() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public int kind() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean you() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createCountResponse(FlatBufferBuilder builder,
      long count,
      int kind,
      boolean you) {
    builder.startTable(3);
    CountResponse.addCount(builder, count);
    CountResponse.addKind(builder, kind);
    CountResponse.addYou(builder, you);
    return CountResponse.endCountResponse(builder);
  }

  public static void startCountResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addCount(FlatBufferBuilder builder, long count) { builder.addInt(0, (int) count, (int) 0L); }
  public static void addKind(FlatBufferBuilder builder, int kind) { builder.addShort(1, (short) kind, (short) 0); }
  public static void addYou(FlatBufferBuilder builder, boolean you) { builder.addBoolean(2, you, false); }
  public static int endCountResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CountResponse get(int j) { return get(new CountResponse(), j); }
    public CountResponse get(CountResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

