// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CounterPipeConfig extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static CounterPipeConfig getRootAsCounterPipeConfig(ByteBuffer _bb) { return getRootAsCounterPipeConfig(_bb, new CounterPipeConfig()); }
  public static CounterPipeConfig getRootAsCounterPipeConfig(ByteBuffer _bb, CounterPipeConfig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CounterPipeConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int kinds(int j) { int o = __offset(4); return o != 0 ? bb.getShort(__vector(o) + j * 2) & 0xFFFF : 0; }
  public int kindsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ShortVector kindsVector() { return kindsVector(new ShortVector()); }
  public ShortVector kindsVector(ShortVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer kindsAsByteBuffer() { return __vector_as_bytebuffer(4, 2); }
  public ByteBuffer kindsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 2); }
  public String pubkey() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createCounterPipeConfig(FlatBufferBuilder builder,
      int kindsOffset,
      int pubkeyOffset) {
    builder.startTable(2);
    CounterPipeConfig.addPubkey(builder, pubkeyOffset);
    CounterPipeConfig.addKinds(builder, kindsOffset);
    return CounterPipeConfig.endCounterPipeConfig(builder);
  }

  public static void startCounterPipeConfig(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addKinds(FlatBufferBuilder builder, int kindsOffset) { builder.addOffset(0, kindsOffset, 0); }
  public static int createKindsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort((short) data[i]); return builder.endVector(); }
  public static void startKindsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(1, pubkeyOffset, 0); }
  public static int endCounterPipeConfig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // kinds
    builder.required(o, 6);  // pubkey
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CounterPipeConfig get(int j) { return get(new CounterPipeConfig(), j); }
    public CounterPipeConfig get(CounterPipeConfig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

