// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DLEQProof extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static DLEQProof getRootAsDLEQProof(ByteBuffer _bb) { return getRootAsDLEQProof(_bb, new DLEQProof()); }
  public static DLEQProof getRootAsDLEQProof(ByteBuffer _bb, DLEQProof obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DLEQProof __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String e() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer eInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String s() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer sInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String r() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer rAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer rInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createDLEQProof(FlatBufferBuilder builder,
      int eOffset,
      int sOffset,
      int rOffset) {
    builder.startTable(3);
    DLEQProof.addR(builder, rOffset);
    DLEQProof.addS(builder, sOffset);
    DLEQProof.addE(builder, eOffset);
    return DLEQProof.endDLEQProof(builder);
  }

  public static void startDLEQProof(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addE(FlatBufferBuilder builder, int eOffset) { builder.addOffset(0, eOffset, 0); }
  public static void addS(FlatBufferBuilder builder, int sOffset) { builder.addOffset(1, sOffset, 0); }
  public static void addR(FlatBufferBuilder builder, int rOffset) { builder.addOffset(2, rOffset, 0); }
  public static int endDLEQProof(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // e
    builder.required(o, 6);  // s
    builder.required(o, 8);  // r
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DLEQProof get(int j) { return get(new DLEQProof(), j); }
    public DLEQProof get(DLEQProof obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

