// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Emoji extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Emoji getRootAsEmoji(ByteBuffer _bb) { return getRootAsEmoji(_bb, new Emoji()); }
  public static Emoji getRootAsEmoji(ByteBuffer _bb, Emoji obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Emoji __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String shortcode() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer shortcodeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer shortcodeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String url() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createEmoji(FlatBufferBuilder builder,
      int shortcodeOffset,
      int urlOffset) {
    builder.startTable(2);
    Emoji.addUrl(builder, urlOffset);
    Emoji.addShortcode(builder, shortcodeOffset);
    return Emoji.endEmoji(builder);
  }

  public static void startEmoji(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addShortcode(FlatBufferBuilder builder, int shortcodeOffset) { builder.addOffset(0, shortcodeOffset, 0); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(1, urlOffset, 0); }
  public static int endEmoji(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // shortcode
    builder.required(o, 6);  // url
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Emoji get(int j) { return get(new Emoji(), j); }
    public Emoji get(Emoji obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

