// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class EmojiData extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static EmojiData getRootAsEmojiData(ByteBuffer _bb) { return getRootAsEmojiData(_bb, new EmojiData()); }
  public static EmojiData getRootAsEmojiData(ByteBuffer _bb, EmojiData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EmojiData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String shortcode() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer shortcodeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer shortcodeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String url() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String emojiSet() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer emojiSetAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer emojiSetInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createEmojiData(FlatBufferBuilder builder,
      int shortcodeOffset,
      int urlOffset,
      int emojiSetOffset) {
    builder.startTable(3);
    EmojiData.addEmojiSet(builder, emojiSetOffset);
    EmojiData.addUrl(builder, urlOffset);
    EmojiData.addShortcode(builder, shortcodeOffset);
    return EmojiData.endEmojiData(builder);
  }

  public static void startEmojiData(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addShortcode(FlatBufferBuilder builder, int shortcodeOffset) { builder.addOffset(0, shortcodeOffset, 0); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(1, urlOffset, 0); }
  public static void addEmojiSet(FlatBufferBuilder builder, int emojiSetOffset) { builder.addOffset(2, emojiSetOffset, 0); }
  public static int endEmojiData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // shortcode
    builder.required(o, 6);  // url
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EmojiData get(int j) { return get(new EmojiData(), j); }
    public EmojiData get(EmojiData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

