// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class EventPointer extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static EventPointer getRootAsEventPointer(ByteBuffer _bb) { return getRootAsEventPointer(_bb, new EventPointer()); }
  public static EventPointer getRootAsEventPointer(ByteBuffer _bb, EventPointer obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EventPointer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String relays(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int relaysLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public StringVector relaysVector() { return relaysVector(new StringVector()); }
  public StringVector relaysVector(StringVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String author() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer authorAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer authorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public long kind() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createEventPointer(FlatBufferBuilder builder,
      int idOffset,
      int relaysOffset,
      int authorOffset,
      long kind) {
    builder.startTable(4);
    EventPointer.addKind(builder, kind);
    EventPointer.addAuthor(builder, authorOffset);
    EventPointer.addRelays(builder, relaysOffset);
    EventPointer.addId(builder, idOffset);
    return EventPointer.endEventPointer(builder);
  }

  public static void startEventPointer(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addRelays(FlatBufferBuilder builder, int relaysOffset) { builder.addOffset(1, relaysOffset, 0); }
  public static int createRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAuthor(FlatBufferBuilder builder, int authorOffset) { builder.addOffset(2, authorOffset, 0); }
  public static void addKind(FlatBufferBuilder builder, long kind) { builder.addLong(3, kind, 0L); }
  public static int endEventPointer(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // id
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EventPointer get(int j) { return get(new EventPointer(), j); }
    public EventPointer get(EventPointer obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

