// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class HistoryTag extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static HistoryTag getRootAsHistoryTag(ByteBuffer _bb) { return getRootAsHistoryTag(_bb, new HistoryTag()); }
  public static HistoryTag getRootAsHistoryTag(ByteBuffer _bb, HistoryTag obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public HistoryTag __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String value() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer valueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String relay() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer relayAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer relayInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String marker() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer markerAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer markerInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createHistoryTag(FlatBufferBuilder builder,
      int nameOffset,
      int valueOffset,
      int relayOffset,
      int markerOffset) {
    builder.startTable(4);
    HistoryTag.addMarker(builder, markerOffset);
    HistoryTag.addRelay(builder, relayOffset);
    HistoryTag.addValue(builder, valueOffset);
    HistoryTag.addName(builder, nameOffset);
    return HistoryTag.endHistoryTag(builder);
  }

  public static void startHistoryTag(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(1, valueOffset, 0); }
  public static void addRelay(FlatBufferBuilder builder, int relayOffset) { builder.addOffset(2, relayOffset, 0); }
  public static void addMarker(FlatBufferBuilder builder, int markerOffset) { builder.addOffset(3, markerOffset, 0); }
  public static int endHistoryTag(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // name
    builder.required(o, 6);  // value
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public HistoryTag get(int j) { return get(new HistoryTag(), j); }
    public HistoryTag get(HistoryTag obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

