// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ImageData extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ImageData getRootAsImageData(ByteBuffer _bb) { return getRootAsImageData(_bb, new ImageData()); }
  public static ImageData getRootAsImageData(ByteBuffer _bb, ImageData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ImageData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String url() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String alt() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer altAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer altInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String dim() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dimAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer dimInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createImageData(FlatBufferBuilder builder,
      int urlOffset,
      int altOffset,
      int dimOffset) {
    builder.startTable(3);
    ImageData.addDim(builder, dimOffset);
    ImageData.addAlt(builder, altOffset);
    ImageData.addUrl(builder, urlOffset);
    return ImageData.endImageData(builder);
  }

  public static void startImageData(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(0, urlOffset, 0); }
  public static void addAlt(FlatBufferBuilder builder, int altOffset) { builder.addOffset(1, altOffset, 0); }
  public static void addDim(FlatBufferBuilder builder, int dimOffset) { builder.addOffset(2, dimOffset, 0); }
  public static int endImageData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // url
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ImageData get(int j) { return get(new ImageData(), j); }
    public ImageData get(ImageData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

