// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ImetaTag extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ImetaTag getRootAsImetaTag(ByteBuffer _bb) { return getRootAsImetaTag(_bb, new ImetaTag()); }
  public static ImetaTag getRootAsImetaTag(ByteBuffer _bb, ImetaTag obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ImetaTag __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String url() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String mimeType() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mimeTypeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer mimeTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String dim() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dimAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer dimInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String alt() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer altAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer altInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String blurhash() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer blurhashAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer blurhashInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String hash() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hashAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer hashInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String fallback(int j) { int o = __offset(16); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int fallbackLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public StringVector fallbackVector() { return fallbackVector(new StringVector()); }
  public StringVector fallbackVector(StringVector obj) { int o = __offset(16); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String annotateUser() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer annotateUserAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer annotateUserInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }

  public static int createImetaTag(FlatBufferBuilder builder,
      int urlOffset,
      int mimeTypeOffset,
      int dimOffset,
      int altOffset,
      int blurhashOffset,
      int hashOffset,
      int fallbackOffset,
      int annotateUserOffset) {
    builder.startTable(8);
    ImetaTag.addAnnotateUser(builder, annotateUserOffset);
    ImetaTag.addFallback(builder, fallbackOffset);
    ImetaTag.addHash(builder, hashOffset);
    ImetaTag.addBlurhash(builder, blurhashOffset);
    ImetaTag.addAlt(builder, altOffset);
    ImetaTag.addDim(builder, dimOffset);
    ImetaTag.addMimeType(builder, mimeTypeOffset);
    ImetaTag.addUrl(builder, urlOffset);
    return ImetaTag.endImetaTag(builder);
  }

  public static void startImetaTag(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(0, urlOffset, 0); }
  public static void addMimeType(FlatBufferBuilder builder, int mimeTypeOffset) { builder.addOffset(1, mimeTypeOffset, 0); }
  public static void addDim(FlatBufferBuilder builder, int dimOffset) { builder.addOffset(2, dimOffset, 0); }
  public static void addAlt(FlatBufferBuilder builder, int altOffset) { builder.addOffset(3, altOffset, 0); }
  public static void addBlurhash(FlatBufferBuilder builder, int blurhashOffset) { builder.addOffset(4, blurhashOffset, 0); }
  public static void addHash(FlatBufferBuilder builder, int hashOffset) { builder.addOffset(5, hashOffset, 0); }
  public static void addFallback(FlatBufferBuilder builder, int fallbackOffset) { builder.addOffset(6, fallbackOffset, 0); }
  public static int createFallbackVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFallbackVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAnnotateUser(FlatBufferBuilder builder, int annotateUserOffset) { builder.addOffset(7, annotateUserOffset, 0); }
  public static int endImetaTag(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // url
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ImetaTag get(int j) { return get(new ImetaTag(), j); }
    public ImetaTag get(ImetaTag obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

