// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind30023Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind30023Parsed getRootAsKind30023Parsed(ByteBuffer _bb) { return getRootAsKind30023Parsed(_bb, new Kind30023Parsed()); }
  public static Kind30023Parsed getRootAsKind30023Parsed(ByteBuffer _bb, Kind30023Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind30023Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String slug() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer slugAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer slugInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String title() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer titleAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer titleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String summary() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer summaryAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer summaryInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String image() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer imageAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer imageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String canonical() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer canonicalAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer canonicalInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String topics(int j) { int o = __offset(14); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int topicsLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public StringVector topicsVector() { return topicsVector(new StringVector()); }
  public StringVector topicsVector(StringVector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public long publishedAt() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String naddr() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer naddrAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer naddrInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public String content() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public nostr.fb.ArticleBlock articleBlocks(int j) { return articleBlocks(new nostr.fb.ArticleBlock(), j); }
  public nostr.fb.ArticleBlock articleBlocks(nostr.fb.ArticleBlock obj, int j) { int o = __offset(22); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int articleBlocksLength() { int o = __offset(22); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ArticleBlock.Vector articleBlocksVector() { return articleBlocksVector(new nostr.fb.ArticleBlock.Vector()); }
  public nostr.fb.ArticleBlock.Vector articleBlocksVector(nostr.fb.ArticleBlock.Vector obj) { int o = __offset(22); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKind30023Parsed(FlatBufferBuilder builder,
      int slugOffset,
      int titleOffset,
      int summaryOffset,
      int imageOffset,
      int canonicalOffset,
      int topicsOffset,
      long publishedAt,
      int naddrOffset,
      int contentOffset,
      int articleBlocksOffset) {
    builder.startTable(10);
    Kind30023Parsed.addPublishedAt(builder, publishedAt);
    Kind30023Parsed.addArticleBlocks(builder, articleBlocksOffset);
    Kind30023Parsed.addContent(builder, contentOffset);
    Kind30023Parsed.addNaddr(builder, naddrOffset);
    Kind30023Parsed.addTopics(builder, topicsOffset);
    Kind30023Parsed.addCanonical(builder, canonicalOffset);
    Kind30023Parsed.addImage(builder, imageOffset);
    Kind30023Parsed.addSummary(builder, summaryOffset);
    Kind30023Parsed.addTitle(builder, titleOffset);
    Kind30023Parsed.addSlug(builder, slugOffset);
    return Kind30023Parsed.endKind30023Parsed(builder);
  }

  public static void startKind30023Parsed(FlatBufferBuilder builder) { builder.startTable(10); }
  public static void addSlug(FlatBufferBuilder builder, int slugOffset) { builder.addOffset(0, slugOffset, 0); }
  public static void addTitle(FlatBufferBuilder builder, int titleOffset) { builder.addOffset(1, titleOffset, 0); }
  public static void addSummary(FlatBufferBuilder builder, int summaryOffset) { builder.addOffset(2, summaryOffset, 0); }
  public static void addImage(FlatBufferBuilder builder, int imageOffset) { builder.addOffset(3, imageOffset, 0); }
  public static void addCanonical(FlatBufferBuilder builder, int canonicalOffset) { builder.addOffset(4, canonicalOffset, 0); }
  public static void addTopics(FlatBufferBuilder builder, int topicsOffset) { builder.addOffset(5, topicsOffset, 0); }
  public static int createTopicsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTopicsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addPublishedAt(FlatBufferBuilder builder, long publishedAt) { builder.addLong(6, publishedAt, 0L); }
  public static void addNaddr(FlatBufferBuilder builder, int naddrOffset) { builder.addOffset(7, naddrOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(8, contentOffset, 0); }
  public static void addArticleBlocks(FlatBufferBuilder builder, int articleBlocksOffset) { builder.addOffset(9, articleBlocksOffset, 0); }
  public static int createArticleBlocksVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startArticleBlocksVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKind30023Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind30023Parsed get(int j) { return get(new Kind30023Parsed(), j); }
    public Kind30023Parsed get(Kind30023Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

