// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind8Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind8Parsed getRootAsKind8Parsed(ByteBuffer _bb) { return getRootAsKind8Parsed(_bb, new Kind8Parsed()); }
  public static Kind8Parsed getRootAsKind8Parsed(ByteBuffer _bb, Kind8Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind8Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String badgeAddress() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer badgeAddressAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer badgeAddressInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String badgeRelay() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer badgeRelayAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer badgeRelayInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public nostr.fb.BadgeAwardRecipient recipients(int j) { return recipients(new nostr.fb.BadgeAwardRecipient(), j); }
  public nostr.fb.BadgeAwardRecipient recipients(nostr.fb.BadgeAwardRecipient obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int recipientsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.BadgeAwardRecipient.Vector recipientsVector() { return recipientsVector(new nostr.fb.BadgeAwardRecipient.Vector()); }
  public nostr.fb.BadgeAwardRecipient.Vector recipientsVector(nostr.fb.BadgeAwardRecipient.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String content() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createKind8Parsed(FlatBufferBuilder builder,
      int badgeAddressOffset,
      int badgeRelayOffset,
      int recipientsOffset,
      int contentOffset) {
    builder.startTable(4);
    Kind8Parsed.addContent(builder, contentOffset);
    Kind8Parsed.addRecipients(builder, recipientsOffset);
    Kind8Parsed.addBadgeRelay(builder, badgeRelayOffset);
    Kind8Parsed.addBadgeAddress(builder, badgeAddressOffset);
    return Kind8Parsed.endKind8Parsed(builder);
  }

  public static void startKind8Parsed(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addBadgeAddress(FlatBufferBuilder builder, int badgeAddressOffset) { builder.addOffset(0, badgeAddressOffset, 0); }
  public static void addBadgeRelay(FlatBufferBuilder builder, int badgeRelayOffset) { builder.addOffset(1, badgeRelayOffset, 0); }
  public static void addRecipients(FlatBufferBuilder builder, int recipientsOffset) { builder.addOffset(2, recipientsOffset, 0); }
  public static int createRecipientsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRecipientsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(3, contentOffset, 0); }
  public static int endKind8Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // badge_address
    builder.required(o, 8);  // recipients
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind8Parsed get(int j) { return get(new Kind8Parsed(), j); }
    public Kind8Parsed get(Kind8Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

