// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind1311Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind1311Parsed getRootAsKind1311Parsed(ByteBuffer _bb) { return getRootAsKind1311Parsed(_bb, new Kind1311Parsed()); }
  public static Kind1311Parsed getRootAsKind1311Parsed(ByteBuffer _bb, Kind1311Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind1311Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String content() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public nostr.fb.ContentBlock parsedContent(int j) { return parsedContent(new nostr.fb.ContentBlock(), j); }
  public nostr.fb.ContentBlock parsedContent(nostr.fb.ContentBlock obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int parsedContentLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ContentBlock.Vector parsedContentVector() { return parsedContentVector(new nostr.fb.ContentBlock.Vector()); }
  public nostr.fb.ContentBlock.Vector parsedContentVector(nostr.fb.ContentBlock.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.LiveActivityRef activity() { return activity(new nostr.fb.LiveActivityRef()); }
  public nostr.fb.LiveActivityRef activity(nostr.fb.LiveActivityRef obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public nostr.fb.LiveChatThreadRef threadRefs(int j) { return threadRefs(new nostr.fb.LiveChatThreadRef(), j); }
  public nostr.fb.LiveChatThreadRef threadRefs(nostr.fb.LiveChatThreadRef obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int threadRefsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.LiveChatThreadRef.Vector threadRefsVector() { return threadRefsVector(new nostr.fb.LiveChatThreadRef.Vector()); }
  public nostr.fb.LiveChatThreadRef.Vector threadRefsVector(nostr.fb.LiveChatThreadRef.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.LiveChatParticipant mentions(int j) { return mentions(new nostr.fb.LiveChatParticipant(), j); }
  public nostr.fb.LiveChatParticipant mentions(nostr.fb.LiveChatParticipant obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int mentionsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.LiveChatParticipant.Vector mentionsVector() { return mentionsVector(new nostr.fb.LiveChatParticipant.Vector()); }
  public nostr.fb.LiveChatParticipant.Vector mentionsVector(nostr.fb.LiveChatParticipant.Vector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKind1311Parsed(FlatBufferBuilder builder,
      int contentOffset,
      int parsedContentOffset,
      int activityOffset,
      int threadRefsOffset,
      int mentionsOffset) {
    builder.startTable(5);
    Kind1311Parsed.addMentions(builder, mentionsOffset);
    Kind1311Parsed.addThreadRefs(builder, threadRefsOffset);
    Kind1311Parsed.addActivity(builder, activityOffset);
    Kind1311Parsed.addParsedContent(builder, parsedContentOffset);
    Kind1311Parsed.addContent(builder, contentOffset);
    return Kind1311Parsed.endKind1311Parsed(builder);
  }

  public static void startKind1311Parsed(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(0, contentOffset, 0); }
  public static void addParsedContent(FlatBufferBuilder builder, int parsedContentOffset) { builder.addOffset(1, parsedContentOffset, 0); }
  public static int createParsedContentVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startParsedContentVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addActivity(FlatBufferBuilder builder, int activityOffset) { builder.addOffset(2, activityOffset, 0); }
  public static void addThreadRefs(FlatBufferBuilder builder, int threadRefsOffset) { builder.addOffset(3, threadRefsOffset, 0); }
  public static int createThreadRefsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startThreadRefsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addMentions(FlatBufferBuilder builder, int mentionsOffset) { builder.addOffset(4, mentionsOffset, 0); }
  public static int createMentionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMentionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKind1311Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // content
    builder.required(o, 8);  // activity
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind1311Parsed get(int j) { return get(new Kind1311Parsed(), j); }
    public Kind1311Parsed get(Kind1311Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

