// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind20Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind20Parsed getRootAsKind20Parsed(ByteBuffer _bb) { return getRootAsKind20Parsed(_bb, new Kind20Parsed()); }
  public static Kind20Parsed getRootAsKind20Parsed(ByteBuffer _bb, Kind20Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind20Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String title() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer titleAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer titleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String description() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public nostr.fb.ImetaTag images(int j) { return images(new nostr.fb.ImetaTag(), j); }
  public nostr.fb.ImetaTag images(nostr.fb.ImetaTag obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int imagesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ImetaTag.Vector imagesVector() { return imagesVector(new nostr.fb.ImetaTag.Vector()); }
  public nostr.fb.ImetaTag.Vector imagesVector(nostr.fb.ImetaTag.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String contentWarning() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentWarningAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer contentWarningInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String location() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer locationAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer locationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String geohash() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer geohashAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer geohashInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String hashtags(int j) { int o = __offset(16); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int hashtagsLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public StringVector hashtagsVector() { return hashtagsVector(new StringVector()); }
  public StringVector hashtagsVector(StringVector obj) { int o = __offset(16); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.ProfilePointer mentions(int j) { return mentions(new nostr.fb.ProfilePointer(), j); }
  public nostr.fb.ProfilePointer mentions(nostr.fb.ProfilePointer obj, int j) { int o = __offset(18); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int mentionsLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ProfilePointer.Vector mentionsVector() { return mentionsVector(new nostr.fb.ProfilePointer.Vector()); }
  public nostr.fb.ProfilePointer.Vector mentionsVector(nostr.fb.ProfilePointer.Vector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKind20Parsed(FlatBufferBuilder builder,
      int titleOffset,
      int descriptionOffset,
      int imagesOffset,
      int contentWarningOffset,
      int locationOffset,
      int geohashOffset,
      int hashtagsOffset,
      int mentionsOffset) {
    builder.startTable(8);
    Kind20Parsed.addMentions(builder, mentionsOffset);
    Kind20Parsed.addHashtags(builder, hashtagsOffset);
    Kind20Parsed.addGeohash(builder, geohashOffset);
    Kind20Parsed.addLocation(builder, locationOffset);
    Kind20Parsed.addContentWarning(builder, contentWarningOffset);
    Kind20Parsed.addImages(builder, imagesOffset);
    Kind20Parsed.addDescription(builder, descriptionOffset);
    Kind20Parsed.addTitle(builder, titleOffset);
    return Kind20Parsed.endKind20Parsed(builder);
  }

  public static void startKind20Parsed(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addTitle(FlatBufferBuilder builder, int titleOffset) { builder.addOffset(0, titleOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(1, descriptionOffset, 0); }
  public static void addImages(FlatBufferBuilder builder, int imagesOffset) { builder.addOffset(2, imagesOffset, 0); }
  public static int createImagesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startImagesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addContentWarning(FlatBufferBuilder builder, int contentWarningOffset) { builder.addOffset(3, contentWarningOffset, 0); }
  public static void addLocation(FlatBufferBuilder builder, int locationOffset) { builder.addOffset(4, locationOffset, 0); }
  public static void addGeohash(FlatBufferBuilder builder, int geohashOffset) { builder.addOffset(5, geohashOffset, 0); }
  public static void addHashtags(FlatBufferBuilder builder, int hashtagsOffset) { builder.addOffset(6, hashtagsOffset, 0); }
  public static int createHashtagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startHashtagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addMentions(FlatBufferBuilder builder, int mentionsOffset) { builder.addOffset(7, mentionsOffset, 0); }
  public static int createMentionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMentionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKind20Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind20Parsed get(int j) { return get(new Kind20Parsed(), j); }
    public Kind20Parsed get(Kind20Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

