// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind1068Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind1068Parsed getRootAsKind1068Parsed(ByteBuffer _bb) { return getRootAsKind1068Parsed(_bb, new Kind1068Parsed()); }
  public static Kind1068Parsed getRootAsKind1068Parsed(ByteBuffer _bb, Kind1068Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind1068Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String pubkey() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String question() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer questionAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer questionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public nostr.fb.ContentBlock contentBlocks(int j) { return contentBlocks(new nostr.fb.ContentBlock(), j); }
  public nostr.fb.ContentBlock contentBlocks(nostr.fb.ContentBlock obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int contentBlocksLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ContentBlock.Vector contentBlocksVector() { return contentBlocksVector(new nostr.fb.ContentBlock.Vector()); }
  public nostr.fb.ContentBlock.Vector contentBlocksVector(nostr.fb.ContentBlock.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.PollOption options(int j) { return options(new nostr.fb.PollOption(), j); }
  public nostr.fb.PollOption options(nostr.fb.PollOption obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int optionsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.PollOption.Vector optionsVector() { return optionsVector(new nostr.fb.PollOption.Vector()); }
  public nostr.fb.PollOption.Vector optionsVector(nostr.fb.PollOption.Vector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public byte pollType() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long endsAt() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String relayUrls(int j) { int o = __offset(18); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int relayUrlsLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public StringVector relayUrlsVector() { return relayUrlsVector(new StringVector()); }
  public StringVector relayUrlsVector(StringVector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKind1068Parsed(FlatBufferBuilder builder,
      int idOffset,
      int pubkeyOffset,
      int questionOffset,
      int contentBlocksOffset,
      int optionsOffset,
      byte pollType,
      long endsAt,
      int relayUrlsOffset) {
    builder.startTable(8);
    Kind1068Parsed.addEndsAt(builder, endsAt);
    Kind1068Parsed.addRelayUrls(builder, relayUrlsOffset);
    Kind1068Parsed.addOptions(builder, optionsOffset);
    Kind1068Parsed.addContentBlocks(builder, contentBlocksOffset);
    Kind1068Parsed.addQuestion(builder, questionOffset);
    Kind1068Parsed.addPubkey(builder, pubkeyOffset);
    Kind1068Parsed.addId(builder, idOffset);
    Kind1068Parsed.addPollType(builder, pollType);
    return Kind1068Parsed.endKind1068Parsed(builder);
  }

  public static void startKind1068Parsed(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(1, pubkeyOffset, 0); }
  public static void addQuestion(FlatBufferBuilder builder, int questionOffset) { builder.addOffset(2, questionOffset, 0); }
  public static void addContentBlocks(FlatBufferBuilder builder, int contentBlocksOffset) { builder.addOffset(3, contentBlocksOffset, 0); }
  public static int createContentBlocksVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startContentBlocksVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addOptions(FlatBufferBuilder builder, int optionsOffset) { builder.addOffset(4, optionsOffset, 0); }
  public static int createOptionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startOptionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addPollType(FlatBufferBuilder builder, byte pollType) { builder.addByte(5, pollType, 0); }
  public static void addEndsAt(FlatBufferBuilder builder, long endsAt) { builder.addLong(6, endsAt, 0L); }
  public static void addRelayUrls(FlatBufferBuilder builder, int relayUrlsOffset) { builder.addOffset(7, relayUrlsOffset, 0); }
  public static int createRelayUrlsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelayUrlsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKind1068Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // id
    builder.required(o, 6);  // pubkey
    builder.required(o, 8);  // question
    builder.required(o, 12);  // options
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind1068Parsed get(int j) { return get(new Kind1068Parsed(), j); }
    public Kind1068Parsed get(Kind1068Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

