// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind3Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind3Parsed getRootAsKind3Parsed(ByteBuffer _bb) { return getRootAsKind3Parsed(_bb, new Kind3Parsed()); }
  public static Kind3Parsed getRootAsKind3Parsed(ByteBuffer _bb, Kind3Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind3Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public nostr.fb.Contact contacts(int j) { return contacts(new nostr.fb.Contact(), j); }
  public nostr.fb.Contact contacts(nostr.fb.Contact obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int contactsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.Contact.Vector contactsVector() { return contactsVector(new nostr.fb.Contact.Vector()); }
  public nostr.fb.Contact.Vector contactsVector(nostr.fb.Contact.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKind3Parsed(FlatBufferBuilder builder,
      int contactsOffset) {
    builder.startTable(1);
    Kind3Parsed.addContacts(builder, contactsOffset);
    return Kind3Parsed.endKind3Parsed(builder);
  }

  public static void startKind3Parsed(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addContacts(FlatBufferBuilder builder, int contactsOffset) { builder.addOffset(0, contactsOffset, 0); }
  public static int createContactsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startContactsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKind3Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // contacts
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind3Parsed get(int j) { return get(new Kind3Parsed(), j); }
    public Kind3Parsed get(Kind3Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

