// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind6Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind6Parsed getRootAsKind6Parsed(ByteBuffer _bb) { return getRootAsKind6Parsed(_bb, new Kind6Parsed()); }
  public static Kind6Parsed getRootAsKind6Parsed(ByteBuffer _bb, Kind6Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind6Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public nostr.fb.ParsedEvent repostedEvent() { return repostedEvent(new nostr.fb.ParsedEvent()); }
  public nostr.fb.ParsedEvent repostedEvent(nostr.fb.ParsedEvent obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createKind6Parsed(FlatBufferBuilder builder,
      int repostedEventOffset) {
    builder.startTable(1);
    Kind6Parsed.addRepostedEvent(builder, repostedEventOffset);
    return Kind6Parsed.endKind6Parsed(builder);
  }

  public static void startKind6Parsed(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addRepostedEvent(FlatBufferBuilder builder, int repostedEventOffset) { builder.addOffset(0, repostedEventOffset, 0); }
  public static int endKind6Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind6Parsed get(int j) { return get(new Kind6Parsed(), j); }
    public Kind6Parsed get(Kind6Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

