// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind9321Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind9321Parsed getRootAsKind9321Parsed(ByteBuffer _bb) { return getRootAsKind9321Parsed(_bb, new Kind9321Parsed()); }
  public static Kind9321Parsed getRootAsKind9321Parsed(ByteBuffer _bb, Kind9321Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind9321Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int amount() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String recipient() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer recipientAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer recipientInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String sender() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer senderAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer senderInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String eventId() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eventIdAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer eventIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String mintUrl() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mintUrlAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer mintUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public boolean redeemed() { int o = __offset(16); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public nostr.fb.Proof proofs(int j) { return proofs(new nostr.fb.Proof(), j); }
  public nostr.fb.Proof proofs(nostr.fb.Proof obj, int j) { int o = __offset(18); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int proofsLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.Proof.Vector proofsVector() { return proofsVector(new nostr.fb.Proof.Vector()); }
  public nostr.fb.Proof.Vector proofsVector(nostr.fb.Proof.Vector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String comment() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer commentAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer commentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public boolean isP2pkLocked() { int o = __offset(22); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String p2pkPubkey() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer p2pkPubkeyAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public ByteBuffer p2pkPubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 1); }

  public static int createKind9321Parsed(FlatBufferBuilder builder,
      int idOffset,
      int amount,
      int recipientOffset,
      int senderOffset,
      int eventIdOffset,
      int mintUrlOffset,
      boolean redeemed,
      int proofsOffset,
      int commentOffset,
      boolean isP2pkLocked,
      int p2pkPubkeyOffset) {
    builder.startTable(11);
    Kind9321Parsed.addP2pkPubkey(builder, p2pkPubkeyOffset);
    Kind9321Parsed.addComment(builder, commentOffset);
    Kind9321Parsed.addProofs(builder, proofsOffset);
    Kind9321Parsed.addMintUrl(builder, mintUrlOffset);
    Kind9321Parsed.addEventId(builder, eventIdOffset);
    Kind9321Parsed.addSender(builder, senderOffset);
    Kind9321Parsed.addRecipient(builder, recipientOffset);
    Kind9321Parsed.addAmount(builder, amount);
    Kind9321Parsed.addId(builder, idOffset);
    Kind9321Parsed.addIsP2pkLocked(builder, isP2pkLocked);
    Kind9321Parsed.addRedeemed(builder, redeemed);
    return Kind9321Parsed.endKind9321Parsed(builder);
  }

  public static void startKind9321Parsed(FlatBufferBuilder builder) { builder.startTable(11); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addAmount(FlatBufferBuilder builder, int amount) { builder.addInt(1, amount, 0); }
  public static void addRecipient(FlatBufferBuilder builder, int recipientOffset) { builder.addOffset(2, recipientOffset, 0); }
  public static void addSender(FlatBufferBuilder builder, int senderOffset) { builder.addOffset(3, senderOffset, 0); }
  public static void addEventId(FlatBufferBuilder builder, int eventIdOffset) { builder.addOffset(4, eventIdOffset, 0); }
  public static void addMintUrl(FlatBufferBuilder builder, int mintUrlOffset) { builder.addOffset(5, mintUrlOffset, 0); }
  public static void addRedeemed(FlatBufferBuilder builder, boolean redeemed) { builder.addBoolean(6, redeemed, false); }
  public static void addProofs(FlatBufferBuilder builder, int proofsOffset) { builder.addOffset(7, proofsOffset, 0); }
  public static int createProofsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startProofsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addComment(FlatBufferBuilder builder, int commentOffset) { builder.addOffset(8, commentOffset, 0); }
  public static void addIsP2pkLocked(FlatBufferBuilder builder, boolean isP2pkLocked) { builder.addBoolean(9, isP2pkLocked, false); }
  public static void addP2pkPubkey(FlatBufferBuilder builder, int p2pkPubkeyOffset) { builder.addOffset(10, p2pkPubkeyOffset, 0); }
  public static int endKind9321Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // id
    builder.required(o, 8);  // recipient
    builder.required(o, 10);  // sender
    builder.required(o, 14);  // mint_url
    builder.required(o, 18);  // proofs
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind9321Parsed get(int j) { return get(new Kind9321Parsed(), j); }
    public Kind9321Parsed get(Kind9321Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

