// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind22Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind22Parsed getRootAsKind22Parsed(ByteBuffer _bb) { return getRootAsKind22Parsed(_bb, new Kind22Parsed()); }
  public static Kind22Parsed getRootAsKind22Parsed(ByteBuffer _bb, Kind22Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind22Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String title() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer titleAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer titleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String description() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public nostr.fb.VideoVariant videos(int j) { return videos(new nostr.fb.VideoVariant(), j); }
  public nostr.fb.VideoVariant videos(nostr.fb.VideoVariant obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int videosLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.VideoVariant.Vector videosVector() { return videosVector(new nostr.fb.VideoVariant.Vector()); }
  public nostr.fb.VideoVariant.Vector videosVector(nostr.fb.VideoVariant.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String alt() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer altAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer altInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String contentWarning() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentWarningAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer contentWarningInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public float duration() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public long publishedAt() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String hashtags(int j) { int o = __offset(18); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int hashtagsLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public StringVector hashtagsVector() { return hashtagsVector(new StringVector()); }
  public StringVector hashtagsVector(StringVector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.ProfilePointer participants(int j) { return participants(new nostr.fb.ProfilePointer(), j); }
  public nostr.fb.ProfilePointer participants(nostr.fb.ProfilePointer obj, int j) { int o = __offset(20); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int participantsLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ProfilePointer.Vector participantsVector() { return participantsVector(new nostr.fb.ProfilePointer.Vector()); }
  public nostr.fb.ProfilePointer.Vector participantsVector(nostr.fb.ProfilePointer.Vector obj) { int o = __offset(20); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKind22Parsed(FlatBufferBuilder builder,
      int titleOffset,
      int descriptionOffset,
      int videosOffset,
      int altOffset,
      int contentWarningOffset,
      float duration,
      long publishedAt,
      int hashtagsOffset,
      int participantsOffset) {
    builder.startTable(9);
    Kind22Parsed.addPublishedAt(builder, publishedAt);
    Kind22Parsed.addParticipants(builder, participantsOffset);
    Kind22Parsed.addHashtags(builder, hashtagsOffset);
    Kind22Parsed.addDuration(builder, duration);
    Kind22Parsed.addContentWarning(builder, contentWarningOffset);
    Kind22Parsed.addAlt(builder, altOffset);
    Kind22Parsed.addVideos(builder, videosOffset);
    Kind22Parsed.addDescription(builder, descriptionOffset);
    Kind22Parsed.addTitle(builder, titleOffset);
    return Kind22Parsed.endKind22Parsed(builder);
  }

  public static void startKind22Parsed(FlatBufferBuilder builder) { builder.startTable(9); }
  public static void addTitle(FlatBufferBuilder builder, int titleOffset) { builder.addOffset(0, titleOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(1, descriptionOffset, 0); }
  public static void addVideos(FlatBufferBuilder builder, int videosOffset) { builder.addOffset(2, videosOffset, 0); }
  public static int createVideosVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startVideosVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAlt(FlatBufferBuilder builder, int altOffset) { builder.addOffset(3, altOffset, 0); }
  public static void addContentWarning(FlatBufferBuilder builder, int contentWarningOffset) { builder.addOffset(4, contentWarningOffset, 0); }
  public static void addDuration(FlatBufferBuilder builder, float duration) { builder.addFloat(5, duration, 0.0f); }
  public static void addPublishedAt(FlatBufferBuilder builder, long publishedAt) { builder.addLong(6, publishedAt, 0L); }
  public static void addHashtags(FlatBufferBuilder builder, int hashtagsOffset) { builder.addOffset(7, hashtagsOffset, 0); }
  public static int createHashtagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startHashtagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addParticipants(FlatBufferBuilder builder, int participantsOffset) { builder.addOffset(8, participantsOffset, 0); }
  public static int createParticipantsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startParticipantsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKind22Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // title
    builder.required(o, 8);  // videos
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind22Parsed get(int j) { return get(new Kind22Parsed(), j); }
    public Kind22Parsed get(Kind22Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

