// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind7Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind7Parsed getRootAsKind7Parsed(ByteBuffer _bb) { return getRootAsKind7Parsed(_bb, new Kind7Parsed()); }
  public static Kind7Parsed getRootAsKind7Parsed(ByteBuffer _bb, Kind7Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind7Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte reactionType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String eventId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eventIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer eventIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String pubkey() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public long eventKind() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public nostr.fb.Emoji emoji() { return emoji(new nostr.fb.Emoji()); }
  public nostr.fb.Emoji emoji(nostr.fb.Emoji obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String targetCoordinates() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer targetCoordinatesAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer targetCoordinatesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }

  public static int createKind7Parsed(FlatBufferBuilder builder,
      byte reactionType,
      int eventIdOffset,
      int pubkeyOffset,
      long eventKind,
      int emojiOffset,
      int targetCoordinatesOffset) {
    builder.startTable(6);
    Kind7Parsed.addEventKind(builder, eventKind);
    Kind7Parsed.addTargetCoordinates(builder, targetCoordinatesOffset);
    Kind7Parsed.addEmoji(builder, emojiOffset);
    Kind7Parsed.addPubkey(builder, pubkeyOffset);
    Kind7Parsed.addEventId(builder, eventIdOffset);
    Kind7Parsed.addReactionType(builder, reactionType);
    return Kind7Parsed.endKind7Parsed(builder);
  }

  public static void startKind7Parsed(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addReactionType(FlatBufferBuilder builder, byte reactionType) { builder.addByte(0, reactionType, 0); }
  public static void addEventId(FlatBufferBuilder builder, int eventIdOffset) { builder.addOffset(1, eventIdOffset, 0); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(2, pubkeyOffset, 0); }
  public static void addEventKind(FlatBufferBuilder builder, long eventKind) { builder.addLong(3, eventKind, 0L); }
  public static void addEmoji(FlatBufferBuilder builder, int emojiOffset) { builder.addOffset(4, emojiOffset, 0); }
  public static void addTargetCoordinates(FlatBufferBuilder builder, int targetCoordinatesOffset) { builder.addOffset(5, targetCoordinatesOffset, 0); }
  public static int endKind7Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // event_id
    builder.required(o, 8);  // pubkey
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind7Parsed get(int j) { return get(new Kind7Parsed(), j); }
    public Kind7Parsed get(Kind7Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

