// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind7374Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind7374Parsed getRootAsKind7374Parsed(ByteBuffer _bb) { return getRootAsKind7374Parsed(_bb, new Kind7374Parsed()); }
  public static Kind7374Parsed getRootAsKind7374Parsed(ByteBuffer _bb, Kind7374Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind7374Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String quoteId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer quoteIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer quoteIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String mintUrl() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mintUrlAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer mintUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long expiration() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createKind7374Parsed(FlatBufferBuilder builder,
      int quoteIdOffset,
      int mintUrlOffset,
      long expiration) {
    builder.startTable(3);
    Kind7374Parsed.addExpiration(builder, expiration);
    Kind7374Parsed.addMintUrl(builder, mintUrlOffset);
    Kind7374Parsed.addQuoteId(builder, quoteIdOffset);
    return Kind7374Parsed.endKind7374Parsed(builder);
  }

  public static void startKind7374Parsed(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addQuoteId(FlatBufferBuilder builder, int quoteIdOffset) { builder.addOffset(0, quoteIdOffset, 0); }
  public static void addMintUrl(FlatBufferBuilder builder, int mintUrlOffset) { builder.addOffset(1, mintUrlOffset, 0); }
  public static void addExpiration(FlatBufferBuilder builder, long expiration) { builder.addLong(2, expiration, 0L); }
  public static int endKind7374Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // quote_id
    builder.required(o, 6);  // mint_url
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind7374Parsed get(int j) { return get(new Kind7374Parsed(), j); }
    public Kind7374Parsed get(Kind7374Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

