// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind0Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind0Parsed getRootAsKind0Parsed(ByteBuffer _bb) { return getRootAsKind0Parsed(_bb, new Kind0Parsed()); }
  public static Kind0Parsed getRootAsKind0Parsed(ByteBuffer _bb, Kind0Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind0Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String pubkey() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String displayName() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer displayNameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer displayNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String picture() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pictureAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer pictureInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String banner() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bannerAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer bannerInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String about() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer aboutAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer aboutInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String website() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer websiteAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer websiteInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public String nip05() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nip05AsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer nip05InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public String lud06() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer lud06AsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer lud06InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public String lud16() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer lud16AsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public ByteBuffer lud16InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 22, 1); }
  public String github() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer githubAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public ByteBuffer githubInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 1); }
  public String twitter() { int o = __offset(26); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer twitterAsByteBuffer() { return __vector_as_bytebuffer(26, 1); }
  public ByteBuffer twitterInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 26, 1); }
  public String mastodon() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mastodonAsByteBuffer() { return __vector_as_bytebuffer(28, 1); }
  public ByteBuffer mastodonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 28, 1); }
  public String nostr() { int o = __offset(30); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nostrAsByteBuffer() { return __vector_as_bytebuffer(30, 1); }
  public ByteBuffer nostrInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 30, 1); }
  public String displayNameAlt() { int o = __offset(32); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer displayNameAltAsByteBuffer() { return __vector_as_bytebuffer(32, 1); }
  public ByteBuffer displayNameAltInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 32, 1); }
  public String username() { int o = __offset(34); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer usernameAsByteBuffer() { return __vector_as_bytebuffer(34, 1); }
  public ByteBuffer usernameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 34, 1); }
  public String bio() { int o = __offset(36); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bioAsByteBuffer() { return __vector_as_bytebuffer(36, 1); }
  public ByteBuffer bioInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 36, 1); }
  public String image() { int o = __offset(38); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer imageAsByteBuffer() { return __vector_as_bytebuffer(38, 1); }
  public ByteBuffer imageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 38, 1); }
  public String avatar() { int o = __offset(40); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer avatarAsByteBuffer() { return __vector_as_bytebuffer(40, 1); }
  public ByteBuffer avatarInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 40, 1); }
  public String background() { int o = __offset(42); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer backgroundAsByteBuffer() { return __vector_as_bytebuffer(42, 1); }
  public ByteBuffer backgroundInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 42, 1); }

  public static int createKind0Parsed(FlatBufferBuilder builder,
      int pubkeyOffset,
      int nameOffset,
      int displayNameOffset,
      int pictureOffset,
      int bannerOffset,
      int aboutOffset,
      int websiteOffset,
      int nip05Offset,
      int lud06Offset,
      int lud16Offset,
      int githubOffset,
      int twitterOffset,
      int mastodonOffset,
      int nostrOffset,
      int displayNameAltOffset,
      int usernameOffset,
      int bioOffset,
      int imageOffset,
      int avatarOffset,
      int backgroundOffset) {
    builder.startTable(20);
    Kind0Parsed.addBackground(builder, backgroundOffset);
    Kind0Parsed.addAvatar(builder, avatarOffset);
    Kind0Parsed.addImage(builder, imageOffset);
    Kind0Parsed.addBio(builder, bioOffset);
    Kind0Parsed.addUsername(builder, usernameOffset);
    Kind0Parsed.addDisplayNameAlt(builder, displayNameAltOffset);
    Kind0Parsed.addNostr(builder, nostrOffset);
    Kind0Parsed.addMastodon(builder, mastodonOffset);
    Kind0Parsed.addTwitter(builder, twitterOffset);
    Kind0Parsed.addGithub(builder, githubOffset);
    Kind0Parsed.addLud16(builder, lud16Offset);
    Kind0Parsed.addLud06(builder, lud06Offset);
    Kind0Parsed.addNip05(builder, nip05Offset);
    Kind0Parsed.addWebsite(builder, websiteOffset);
    Kind0Parsed.addAbout(builder, aboutOffset);
    Kind0Parsed.addBanner(builder, bannerOffset);
    Kind0Parsed.addPicture(builder, pictureOffset);
    Kind0Parsed.addDisplayName(builder, displayNameOffset);
    Kind0Parsed.addName(builder, nameOffset);
    Kind0Parsed.addPubkey(builder, pubkeyOffset);
    return Kind0Parsed.endKind0Parsed(builder);
  }

  public static void startKind0Parsed(FlatBufferBuilder builder) { builder.startTable(20); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(0, pubkeyOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addDisplayName(FlatBufferBuilder builder, int displayNameOffset) { builder.addOffset(2, displayNameOffset, 0); }
  public static void addPicture(FlatBufferBuilder builder, int pictureOffset) { builder.addOffset(3, pictureOffset, 0); }
  public static void addBanner(FlatBufferBuilder builder, int bannerOffset) { builder.addOffset(4, bannerOffset, 0); }
  public static void addAbout(FlatBufferBuilder builder, int aboutOffset) { builder.addOffset(5, aboutOffset, 0); }
  public static void addWebsite(FlatBufferBuilder builder, int websiteOffset) { builder.addOffset(6, websiteOffset, 0); }
  public static void addNip05(FlatBufferBuilder builder, int nip05Offset) { builder.addOffset(7, nip05Offset, 0); }
  public static void addLud06(FlatBufferBuilder builder, int lud06Offset) { builder.addOffset(8, lud06Offset, 0); }
  public static void addLud16(FlatBufferBuilder builder, int lud16Offset) { builder.addOffset(9, lud16Offset, 0); }
  public static void addGithub(FlatBufferBuilder builder, int githubOffset) { builder.addOffset(10, githubOffset, 0); }
  public static void addTwitter(FlatBufferBuilder builder, int twitterOffset) { builder.addOffset(11, twitterOffset, 0); }
  public static void addMastodon(FlatBufferBuilder builder, int mastodonOffset) { builder.addOffset(12, mastodonOffset, 0); }
  public static void addNostr(FlatBufferBuilder builder, int nostrOffset) { builder.addOffset(13, nostrOffset, 0); }
  public static void addDisplayNameAlt(FlatBufferBuilder builder, int displayNameAltOffset) { builder.addOffset(14, displayNameAltOffset, 0); }
  public static void addUsername(FlatBufferBuilder builder, int usernameOffset) { builder.addOffset(15, usernameOffset, 0); }
  public static void addBio(FlatBufferBuilder builder, int bioOffset) { builder.addOffset(16, bioOffset, 0); }
  public static void addImage(FlatBufferBuilder builder, int imageOffset) { builder.addOffset(17, imageOffset, 0); }
  public static void addAvatar(FlatBufferBuilder builder, int avatarOffset) { builder.addOffset(18, avatarOffset, 0); }
  public static void addBackground(FlatBufferBuilder builder, int backgroundOffset) { builder.addOffset(19, backgroundOffset, 0); }
  public static int endKind0Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind0Parsed get(int j) { return get(new Kind0Parsed(), j); }
    public Kind0Parsed get(Kind0Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

