// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind7376Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind7376Parsed getRootAsKind7376Parsed(ByteBuffer _bb) { return getRootAsKind7376Parsed(_bb, new Kind7376Parsed()); }
  public static Kind7376Parsed getRootAsKind7376Parsed(ByteBuffer _bb, Kind7376Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind7376Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String direction() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer directionAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer directionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int amount() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String createdEvents(int j) { int o = __offset(8); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int createdEventsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public StringVector createdEventsVector() { return createdEventsVector(new StringVector()); }
  public StringVector createdEventsVector(StringVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String destroyedEvents(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int destroyedEventsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public StringVector destroyedEventsVector() { return destroyedEventsVector(new StringVector()); }
  public StringVector destroyedEventsVector(StringVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String redeemedEvents(int j) { int o = __offset(12); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int redeemedEventsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public StringVector redeemedEventsVector() { return redeemedEventsVector(new StringVector()); }
  public StringVector redeemedEventsVector(StringVector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.HistoryTag tags(int j) { return tags(new nostr.fb.HistoryTag(), j); }
  public nostr.fb.HistoryTag tags(nostr.fb.HistoryTag obj, int j) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int tagsLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.HistoryTag.Vector tagsVector() { return tagsVector(new nostr.fb.HistoryTag.Vector()); }
  public nostr.fb.HistoryTag.Vector tagsVector(nostr.fb.HistoryTag.Vector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public boolean decrypted() { int o = __offset(16); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createKind7376Parsed(FlatBufferBuilder builder,
      int directionOffset,
      int amount,
      int createdEventsOffset,
      int destroyedEventsOffset,
      int redeemedEventsOffset,
      int tagsOffset,
      boolean decrypted) {
    builder.startTable(7);
    Kind7376Parsed.addTags(builder, tagsOffset);
    Kind7376Parsed.addRedeemedEvents(builder, redeemedEventsOffset);
    Kind7376Parsed.addDestroyedEvents(builder, destroyedEventsOffset);
    Kind7376Parsed.addCreatedEvents(builder, createdEventsOffset);
    Kind7376Parsed.addAmount(builder, amount);
    Kind7376Parsed.addDirection(builder, directionOffset);
    Kind7376Parsed.addDecrypted(builder, decrypted);
    return Kind7376Parsed.endKind7376Parsed(builder);
  }

  public static void startKind7376Parsed(FlatBufferBuilder builder) { builder.startTable(7); }
  public static void addDirection(FlatBufferBuilder builder, int directionOffset) { builder.addOffset(0, directionOffset, 0); }
  public static void addAmount(FlatBufferBuilder builder, int amount) { builder.addInt(1, amount, 0); }
  public static void addCreatedEvents(FlatBufferBuilder builder, int createdEventsOffset) { builder.addOffset(2, createdEventsOffset, 0); }
  public static int createCreatedEventsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCreatedEventsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addDestroyedEvents(FlatBufferBuilder builder, int destroyedEventsOffset) { builder.addOffset(3, destroyedEventsOffset, 0); }
  public static int createDestroyedEventsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDestroyedEventsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRedeemedEvents(FlatBufferBuilder builder, int redeemedEventsOffset) { builder.addOffset(4, redeemedEventsOffset, 0); }
  public static int createRedeemedEventsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRedeemedEventsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTags(FlatBufferBuilder builder, int tagsOffset) { builder.addOffset(5, tagsOffset, 0); }
  public static int createTagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addDecrypted(FlatBufferBuilder builder, boolean decrypted) { builder.addBoolean(6, decrypted, false); }
  public static int endKind7376Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // direction
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind7376Parsed get(int j) { return get(new Kind7376Parsed(), j); }
    public Kind7376Parsed get(Kind7376Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

