// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind9735Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind9735Parsed getRootAsKind9735Parsed(ByteBuffer _bb) { return getRootAsKind9735Parsed(_bb, new Kind9735Parsed()); }
  public static Kind9735Parsed getRootAsKind9735Parsed(ByteBuffer _bb, Kind9735Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind9735Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int amount() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String content() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String bolt11() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bolt11AsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer bolt11InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String preimage() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer preimageAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer preimageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String sender() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer senderAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer senderInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String recipient() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer recipientAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer recipientInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public String event() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eventAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer eventInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public String eventCoordinate() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eventCoordinateAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer eventCoordinateInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public long timestamp() { int o = __offset(22); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean valid() { int o = __offset(24); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public nostr.fb.ZapRequest description() { return description(new nostr.fb.ZapRequest()); }
  public nostr.fb.ZapRequest description(nostr.fb.ZapRequest obj) { int o = __offset(26); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createKind9735Parsed(FlatBufferBuilder builder,
      int idOffset,
      int amount,
      int contentOffset,
      int bolt11Offset,
      int preimageOffset,
      int senderOffset,
      int recipientOffset,
      int eventOffset,
      int eventCoordinateOffset,
      long timestamp,
      boolean valid,
      int descriptionOffset) {
    builder.startTable(12);
    Kind9735Parsed.addTimestamp(builder, timestamp);
    Kind9735Parsed.addDescription(builder, descriptionOffset);
    Kind9735Parsed.addEventCoordinate(builder, eventCoordinateOffset);
    Kind9735Parsed.addEvent(builder, eventOffset);
    Kind9735Parsed.addRecipient(builder, recipientOffset);
    Kind9735Parsed.addSender(builder, senderOffset);
    Kind9735Parsed.addPreimage(builder, preimageOffset);
    Kind9735Parsed.addBolt11(builder, bolt11Offset);
    Kind9735Parsed.addContent(builder, contentOffset);
    Kind9735Parsed.addAmount(builder, amount);
    Kind9735Parsed.addId(builder, idOffset);
    Kind9735Parsed.addValid(builder, valid);
    return Kind9735Parsed.endKind9735Parsed(builder);
  }

  public static void startKind9735Parsed(FlatBufferBuilder builder) { builder.startTable(12); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addAmount(FlatBufferBuilder builder, int amount) { builder.addInt(1, amount, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(2, contentOffset, 0); }
  public static void addBolt11(FlatBufferBuilder builder, int bolt11Offset) { builder.addOffset(3, bolt11Offset, 0); }
  public static void addPreimage(FlatBufferBuilder builder, int preimageOffset) { builder.addOffset(4, preimageOffset, 0); }
  public static void addSender(FlatBufferBuilder builder, int senderOffset) { builder.addOffset(5, senderOffset, 0); }
  public static void addRecipient(FlatBufferBuilder builder, int recipientOffset) { builder.addOffset(6, recipientOffset, 0); }
  public static void addEvent(FlatBufferBuilder builder, int eventOffset) { builder.addOffset(7, eventOffset, 0); }
  public static void addEventCoordinate(FlatBufferBuilder builder, int eventCoordinateOffset) { builder.addOffset(8, eventCoordinateOffset, 0); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(9, timestamp, 0L); }
  public static void addValid(FlatBufferBuilder builder, boolean valid) { builder.addBoolean(10, valid, false); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(11, descriptionOffset, 0); }
  public static int endKind9735Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // id
    builder.required(o, 8);  // content
    builder.required(o, 10);  // bolt11
    builder.required(o, 14);  // sender
    builder.required(o, 16);  // recipient
    builder.required(o, 26);  // description
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind9735Parsed get(int j) { return get(new Kind9735Parsed(), j); }
    public Kind9735Parsed get(Kind9735Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

