// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind1018Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind1018Parsed getRootAsKind1018Parsed(ByteBuffer _bb) { return getRootAsKind1018Parsed(_bb, new Kind1018Parsed()); }
  public static Kind1018Parsed getRootAsKind1018Parsed(ByteBuffer _bb, Kind1018Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind1018Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String pubkey() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String pollEventId() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pollEventIdAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer pollEventIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String selectedOptions(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int selectedOptionsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public StringVector selectedOptionsVector() { return selectedOptionsVector(new StringVector()); }
  public StringVector selectedOptionsVector(StringVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKind1018Parsed(FlatBufferBuilder builder,
      int idOffset,
      int pubkeyOffset,
      int pollEventIdOffset,
      int selectedOptionsOffset) {
    builder.startTable(4);
    Kind1018Parsed.addSelectedOptions(builder, selectedOptionsOffset);
    Kind1018Parsed.addPollEventId(builder, pollEventIdOffset);
    Kind1018Parsed.addPubkey(builder, pubkeyOffset);
    Kind1018Parsed.addId(builder, idOffset);
    return Kind1018Parsed.endKind1018Parsed(builder);
  }

  public static void startKind1018Parsed(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(1, pubkeyOffset, 0); }
  public static void addPollEventId(FlatBufferBuilder builder, int pollEventIdOffset) { builder.addOffset(2, pollEventIdOffset, 0); }
  public static void addSelectedOptions(FlatBufferBuilder builder, int selectedOptionsOffset) { builder.addOffset(3, selectedOptionsOffset, 0); }
  public static int createSelectedOptionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSelectedOptionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKind1018Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // id
    builder.required(o, 6);  // pubkey
    builder.required(o, 8);  // poll_event_id
    builder.required(o, 10);  // selected_options
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind1018Parsed get(int j) { return get(new Kind1018Parsed(), j); }
    public Kind1018Parsed get(Kind1018Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

