// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind17375Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind17375Parsed getRootAsKind17375Parsed(ByteBuffer _bb) { return getRootAsKind17375Parsed(_bb, new Kind17375Parsed()); }
  public static Kind17375Parsed getRootAsKind17375Parsed(ByteBuffer _bb, Kind17375Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind17375Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String mints(int j) { int o = __offset(4); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int mintsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public StringVector mintsVector() { return mintsVector(new StringVector()); }
  public StringVector mintsVector(StringVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String p2pkPrivKey() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer p2pkPrivKeyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer p2pkPrivKeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String p2pkPubKey() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer p2pkPubKeyAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer p2pkPubKeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public boolean decrypted() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createKind17375Parsed(FlatBufferBuilder builder,
      int mintsOffset,
      int p2pkPrivKeyOffset,
      int p2pkPubKeyOffset,
      boolean decrypted) {
    builder.startTable(4);
    Kind17375Parsed.addP2pkPubKey(builder, p2pkPubKeyOffset);
    Kind17375Parsed.addP2pkPrivKey(builder, p2pkPrivKeyOffset);
    Kind17375Parsed.addMints(builder, mintsOffset);
    Kind17375Parsed.addDecrypted(builder, decrypted);
    return Kind17375Parsed.endKind17375Parsed(builder);
  }

  public static void startKind17375Parsed(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addMints(FlatBufferBuilder builder, int mintsOffset) { builder.addOffset(0, mintsOffset, 0); }
  public static int createMintsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMintsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addP2pkPrivKey(FlatBufferBuilder builder, int p2pkPrivKeyOffset) { builder.addOffset(1, p2pkPrivKeyOffset, 0); }
  public static void addP2pkPubKey(FlatBufferBuilder builder, int p2pkPubKeyOffset) { builder.addOffset(2, p2pkPubKeyOffset, 0); }
  public static void addDecrypted(FlatBufferBuilder builder, boolean decrypted) { builder.addBoolean(3, decrypted, false); }
  public static int endKind17375Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // mints
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind17375Parsed get(int j) { return get(new Kind17375Parsed(), j); }
    public Kind17375Parsed get(Kind17375Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

