// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind4Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind4Parsed getRootAsKind4Parsed(ByteBuffer _bb) { return getRootAsKind4Parsed(_bb, new Kind4Parsed()); }
  public static Kind4Parsed getRootAsKind4Parsed(ByteBuffer _bb, Kind4Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind4Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public nostr.fb.ContentBlock parsedContent(int j) { return parsedContent(new nostr.fb.ContentBlock(), j); }
  public nostr.fb.ContentBlock parsedContent(nostr.fb.ContentBlock obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int parsedContentLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ContentBlock.Vector parsedContentVector() { return parsedContentVector(new nostr.fb.ContentBlock.Vector()); }
  public nostr.fb.ContentBlock.Vector parsedContentVector(nostr.fb.ContentBlock.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String decryptedContent() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer decryptedContentAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer decryptedContentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String chatId() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer chatIdAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer chatIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String recipient() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer recipientAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer recipientInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createKind4Parsed(FlatBufferBuilder builder,
      int parsedContentOffset,
      int decryptedContentOffset,
      int chatIdOffset,
      int recipientOffset) {
    builder.startTable(4);
    Kind4Parsed.addRecipient(builder, recipientOffset);
    Kind4Parsed.addChatId(builder, chatIdOffset);
    Kind4Parsed.addDecryptedContent(builder, decryptedContentOffset);
    Kind4Parsed.addParsedContent(builder, parsedContentOffset);
    return Kind4Parsed.endKind4Parsed(builder);
  }

  public static void startKind4Parsed(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addParsedContent(FlatBufferBuilder builder, int parsedContentOffset) { builder.addOffset(0, parsedContentOffset, 0); }
  public static int createParsedContentVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startParsedContentVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addDecryptedContent(FlatBufferBuilder builder, int decryptedContentOffset) { builder.addOffset(1, decryptedContentOffset, 0); }
  public static void addChatId(FlatBufferBuilder builder, int chatIdOffset) { builder.addOffset(2, chatIdOffset, 0); }
  public static void addRecipient(FlatBufferBuilder builder, int recipientOffset) { builder.addOffset(3, recipientOffset, 0); }
  public static int endKind4Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 8);  // chat_id
    builder.required(o, 10);  // recipient
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind4Parsed get(int j) { return get(new Kind4Parsed(), j); }
    public Kind4Parsed get(Kind4Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

