// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind7375Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind7375Parsed getRootAsKind7375Parsed(ByteBuffer _bb) { return getRootAsKind7375Parsed(_bb, new Kind7375Parsed()); }
  public static Kind7375Parsed getRootAsKind7375Parsed(ByteBuffer _bb, Kind7375Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind7375Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String mintUrl() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mintUrlAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer mintUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public nostr.fb.Proof proofs(int j) { return proofs(new nostr.fb.Proof(), j); }
  public nostr.fb.Proof proofs(nostr.fb.Proof obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int proofsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.Proof.Vector proofsVector() { return proofsVector(new nostr.fb.Proof.Vector()); }
  public nostr.fb.Proof.Vector proofsVector(nostr.fb.Proof.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String deletedIds(int j) { int o = __offset(8); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int deletedIdsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public StringVector deletedIdsVector() { return deletedIdsVector(new StringVector()); }
  public StringVector deletedIdsVector(StringVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public boolean decrypted() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createKind7375Parsed(FlatBufferBuilder builder,
      int mintUrlOffset,
      int proofsOffset,
      int deletedIdsOffset,
      boolean decrypted) {
    builder.startTable(4);
    Kind7375Parsed.addDeletedIds(builder, deletedIdsOffset);
    Kind7375Parsed.addProofs(builder, proofsOffset);
    Kind7375Parsed.addMintUrl(builder, mintUrlOffset);
    Kind7375Parsed.addDecrypted(builder, decrypted);
    return Kind7375Parsed.endKind7375Parsed(builder);
  }

  public static void startKind7375Parsed(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addMintUrl(FlatBufferBuilder builder, int mintUrlOffset) { builder.addOffset(0, mintUrlOffset, 0); }
  public static void addProofs(FlatBufferBuilder builder, int proofsOffset) { builder.addOffset(1, proofsOffset, 0); }
  public static int createProofsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startProofsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addDeletedIds(FlatBufferBuilder builder, int deletedIdsOffset) { builder.addOffset(2, deletedIdsOffset, 0); }
  public static int createDeletedIdsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDeletedIdsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addDecrypted(FlatBufferBuilder builder, boolean decrypted) { builder.addBoolean(3, decrypted, false); }
  public static int endKind7375Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // mint_url
    builder.required(o, 6);  // proofs
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind7375Parsed get(int j) { return get(new Kind7375Parsed(), j); }
    public Kind7375Parsed get(Kind7375Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

