// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind1111Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind1111Parsed getRootAsKind1111Parsed(ByteBuffer _bb) { return getRootAsKind1111Parsed(_bb, new Kind1111Parsed()); }
  public static Kind1111Parsed getRootAsKind1111Parsed(ByteBuffer _bb, Kind1111Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind1111Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String content() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public nostr.fb.ContentBlock parsedContent(int j) { return parsedContent(new nostr.fb.ContentBlock(), j); }
  public nostr.fb.ContentBlock parsedContent(nostr.fb.ContentBlock obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int parsedContentLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ContentBlock.Vector parsedContentVector() { return parsedContentVector(new nostr.fb.ContentBlock.Vector()); }
  public nostr.fb.ContentBlock.Vector parsedContentVector(nostr.fb.ContentBlock.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String rootId() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer rootIdAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer rootIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String rootCoordinate() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer rootCoordinateAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer rootCoordinateInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String rootExternal() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer rootExternalAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer rootExternalInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public int rootKind() { int o = __offset(14); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public String rootAuthor() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer rootAuthorAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer rootAuthorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public String rootRelays(int j) { int o = __offset(18); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int rootRelaysLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public StringVector rootRelaysVector() { return rootRelaysVector(new StringVector()); }
  public StringVector rootRelaysVector(StringVector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String parentId() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer parentIdAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer parentIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public String parentCoordinate() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer parentCoordinateAsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public ByteBuffer parentCoordinateInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 22, 1); }
  public String parentExternal() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer parentExternalAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public ByteBuffer parentExternalInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 1); }
  public int parentKind() { int o = __offset(26); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public String parentAuthor() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer parentAuthorAsByteBuffer() { return __vector_as_bytebuffer(28, 1); }
  public ByteBuffer parentAuthorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 28, 1); }
  public String parentRelays(int j) { int o = __offset(30); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int parentRelaysLength() { int o = __offset(30); return o != 0 ? __vector_len(o) : 0; }
  public StringVector parentRelaysVector() { return parentRelaysVector(new StringVector()); }
  public StringVector parentRelaysVector(StringVector obj) { int o = __offset(30); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.EventPointer citations(int j) { return citations(new nostr.fb.EventPointer(), j); }
  public nostr.fb.EventPointer citations(nostr.fb.EventPointer obj, int j) { int o = __offset(32); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int citationsLength() { int o = __offset(32); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.EventPointer.Vector citationsVector() { return citationsVector(new nostr.fb.EventPointer.Vector()); }
  public nostr.fb.EventPointer.Vector citationsVector(nostr.fb.EventPointer.Vector obj) { int o = __offset(32); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.ProfilePointer mentions(int j) { return mentions(new nostr.fb.ProfilePointer(), j); }
  public nostr.fb.ProfilePointer mentions(nostr.fb.ProfilePointer obj, int j) { int o = __offset(34); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int mentionsLength() { int o = __offset(34); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ProfilePointer.Vector mentionsVector() { return mentionsVector(new nostr.fb.ProfilePointer.Vector()); }
  public nostr.fb.ProfilePointer.Vector mentionsVector(nostr.fb.ProfilePointer.Vector obj) { int o = __offset(34); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKind1111Parsed(FlatBufferBuilder builder,
      int contentOffset,
      int parsedContentOffset,
      int rootIdOffset,
      int rootCoordinateOffset,
      int rootExternalOffset,
      int rootKind,
      int rootAuthorOffset,
      int rootRelaysOffset,
      int parentIdOffset,
      int parentCoordinateOffset,
      int parentExternalOffset,
      int parentKind,
      int parentAuthorOffset,
      int parentRelaysOffset,
      int citationsOffset,
      int mentionsOffset) {
    builder.startTable(16);
    Kind1111Parsed.addMentions(builder, mentionsOffset);
    Kind1111Parsed.addCitations(builder, citationsOffset);
    Kind1111Parsed.addParentRelays(builder, parentRelaysOffset);
    Kind1111Parsed.addParentAuthor(builder, parentAuthorOffset);
    Kind1111Parsed.addParentExternal(builder, parentExternalOffset);
    Kind1111Parsed.addParentCoordinate(builder, parentCoordinateOffset);
    Kind1111Parsed.addParentId(builder, parentIdOffset);
    Kind1111Parsed.addRootRelays(builder, rootRelaysOffset);
    Kind1111Parsed.addRootAuthor(builder, rootAuthorOffset);
    Kind1111Parsed.addRootExternal(builder, rootExternalOffset);
    Kind1111Parsed.addRootCoordinate(builder, rootCoordinateOffset);
    Kind1111Parsed.addRootId(builder, rootIdOffset);
    Kind1111Parsed.addParsedContent(builder, parsedContentOffset);
    Kind1111Parsed.addContent(builder, contentOffset);
    Kind1111Parsed.addParentKind(builder, parentKind);
    Kind1111Parsed.addRootKind(builder, rootKind);
    return Kind1111Parsed.endKind1111Parsed(builder);
  }

  public static void startKind1111Parsed(FlatBufferBuilder builder) { builder.startTable(16); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(0, contentOffset, 0); }
  public static void addParsedContent(FlatBufferBuilder builder, int parsedContentOffset) { builder.addOffset(1, parsedContentOffset, 0); }
  public static int createParsedContentVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startParsedContentVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRootId(FlatBufferBuilder builder, int rootIdOffset) { builder.addOffset(2, rootIdOffset, 0); }
  public static void addRootCoordinate(FlatBufferBuilder builder, int rootCoordinateOffset) { builder.addOffset(3, rootCoordinateOffset, 0); }
  public static void addRootExternal(FlatBufferBuilder builder, int rootExternalOffset) { builder.addOffset(4, rootExternalOffset, 0); }
  public static void addRootKind(FlatBufferBuilder builder, int rootKind) { builder.addShort(5, (short) rootKind, (short) 0); }
  public static void addRootAuthor(FlatBufferBuilder builder, int rootAuthorOffset) { builder.addOffset(6, rootAuthorOffset, 0); }
  public static void addRootRelays(FlatBufferBuilder builder, int rootRelaysOffset) { builder.addOffset(7, rootRelaysOffset, 0); }
  public static int createRootRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRootRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addParentId(FlatBufferBuilder builder, int parentIdOffset) { builder.addOffset(8, parentIdOffset, 0); }
  public static void addParentCoordinate(FlatBufferBuilder builder, int parentCoordinateOffset) { builder.addOffset(9, parentCoordinateOffset, 0); }
  public static void addParentExternal(FlatBufferBuilder builder, int parentExternalOffset) { builder.addOffset(10, parentExternalOffset, 0); }
  public static void addParentKind(FlatBufferBuilder builder, int parentKind) { builder.addShort(11, (short) parentKind, (short) 0); }
  public static void addParentAuthor(FlatBufferBuilder builder, int parentAuthorOffset) { builder.addOffset(12, parentAuthorOffset, 0); }
  public static void addParentRelays(FlatBufferBuilder builder, int parentRelaysOffset) { builder.addOffset(13, parentRelaysOffset, 0); }
  public static int createParentRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startParentRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addCitations(FlatBufferBuilder builder, int citationsOffset) { builder.addOffset(14, citationsOffset, 0); }
  public static int createCitationsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCitationsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addMentions(FlatBufferBuilder builder, int mentionsOffset) { builder.addOffset(15, mentionsOffset, 0); }
  public static int createMentionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMentionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKind1111Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // content
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind1111Parsed get(int j) { return get(new Kind1111Parsed(), j); }
    public Kind1111Parsed get(Kind1111Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

