// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind1Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind1Parsed getRootAsKind1Parsed(ByteBuffer _bb) { return getRootAsKind1Parsed(_bb, new Kind1Parsed()); }
  public static Kind1Parsed getRootAsKind1Parsed(ByteBuffer _bb, Kind1Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind1Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public nostr.fb.ContentBlock parsedContent(int j) { return parsedContent(new nostr.fb.ContentBlock(), j); }
  public nostr.fb.ContentBlock parsedContent(nostr.fb.ContentBlock obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int parsedContentLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ContentBlock.Vector parsedContentVector() { return parsedContentVector(new nostr.fb.ContentBlock.Vector()); }
  public nostr.fb.ContentBlock.Vector parsedContentVector(nostr.fb.ContentBlock.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.ContentBlock shortenedContent(int j) { return shortenedContent(new nostr.fb.ContentBlock(), j); }
  public nostr.fb.ContentBlock shortenedContent(nostr.fb.ContentBlock obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int shortenedContentLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ContentBlock.Vector shortenedContentVector() { return shortenedContentVector(new nostr.fb.ContentBlock.Vector()); }
  public nostr.fb.ContentBlock.Vector shortenedContentVector(nostr.fb.ContentBlock.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.ProfilePointer profileMentions(int j) { return profileMentions(new nostr.fb.ProfilePointer(), j); }
  public nostr.fb.ProfilePointer profileMentions(nostr.fb.ProfilePointer obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int profileMentionsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.ProfilePointer.Vector profileMentionsVector() { return profileMentionsVector(new nostr.fb.ProfilePointer.Vector()); }
  public nostr.fb.ProfilePointer.Vector profileMentionsVector(nostr.fb.ProfilePointer.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.EventPointer eventRefs(int j) { return eventRefs(new nostr.fb.EventPointer(), j); }
  public nostr.fb.EventPointer eventRefs(nostr.fb.EventPointer obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int eventRefsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.EventPointer.Vector eventRefsVector() { return eventRefsVector(new nostr.fb.EventPointer.Vector()); }
  public nostr.fb.EventPointer.Vector eventRefsVector(nostr.fb.EventPointer.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.AddressPointer addressRefs(int j) { return addressRefs(new nostr.fb.AddressPointer(), j); }
  public nostr.fb.AddressPointer addressRefs(nostr.fb.AddressPointer obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int addressRefsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.AddressPointer.Vector addressRefsVector() { return addressRefsVector(new nostr.fb.AddressPointer.Vector()); }
  public nostr.fb.AddressPointer.Vector addressRefsVector(nostr.fb.AddressPointer.Vector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.EventPointer reply() { return reply(new nostr.fb.EventPointer()); }
  public nostr.fb.EventPointer reply(nostr.fb.EventPointer obj) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public nostr.fb.EventPointer root() { return root(new nostr.fb.EventPointer()); }
  public nostr.fb.EventPointer root(nostr.fb.EventPointer obj) { int o = __offset(16); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createKind1Parsed(FlatBufferBuilder builder,
      int parsedContentOffset,
      int shortenedContentOffset,
      int profileMentionsOffset,
      int eventRefsOffset,
      int addressRefsOffset,
      int replyOffset,
      int rootOffset) {
    builder.startTable(7);
    Kind1Parsed.addRoot(builder, rootOffset);
    Kind1Parsed.addReply(builder, replyOffset);
    Kind1Parsed.addAddressRefs(builder, addressRefsOffset);
    Kind1Parsed.addEventRefs(builder, eventRefsOffset);
    Kind1Parsed.addProfileMentions(builder, profileMentionsOffset);
    Kind1Parsed.addShortenedContent(builder, shortenedContentOffset);
    Kind1Parsed.addParsedContent(builder, parsedContentOffset);
    return Kind1Parsed.endKind1Parsed(builder);
  }

  public static void startKind1Parsed(FlatBufferBuilder builder) { builder.startTable(7); }
  public static void addParsedContent(FlatBufferBuilder builder, int parsedContentOffset) { builder.addOffset(0, parsedContentOffset, 0); }
  public static int createParsedContentVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startParsedContentVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addShortenedContent(FlatBufferBuilder builder, int shortenedContentOffset) { builder.addOffset(1, shortenedContentOffset, 0); }
  public static int createShortenedContentVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startShortenedContentVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addProfileMentions(FlatBufferBuilder builder, int profileMentionsOffset) { builder.addOffset(2, profileMentionsOffset, 0); }
  public static int createProfileMentionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startProfileMentionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addEventRefs(FlatBufferBuilder builder, int eventRefsOffset) { builder.addOffset(3, eventRefsOffset, 0); }
  public static int createEventRefsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEventRefsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAddressRefs(FlatBufferBuilder builder, int addressRefsOffset) { builder.addOffset(4, addressRefsOffset, 0); }
  public static int createAddressRefsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAddressRefsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addReply(FlatBufferBuilder builder, int replyOffset) { builder.addOffset(5, replyOffset, 0); }
  public static void addRoot(FlatBufferBuilder builder, int rootOffset) { builder.addOffset(6, rootOffset, 0); }
  public static int endKind1Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // parsed_content
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind1Parsed get(int j) { return get(new Kind1Parsed(), j); }
    public Kind1Parsed get(Kind1Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

