// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Kind10002Parsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Kind10002Parsed getRootAsKind10002Parsed(ByteBuffer _bb) { return getRootAsKind10002Parsed(_bb, new Kind10002Parsed()); }
  public static Kind10002Parsed getRootAsKind10002Parsed(ByteBuffer _bb, Kind10002Parsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Kind10002Parsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public nostr.fb.RelayInfo relays(int j) { return relays(new nostr.fb.RelayInfo(), j); }
  public nostr.fb.RelayInfo relays(nostr.fb.RelayInfo obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int relaysLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.RelayInfo.Vector relaysVector() { return relaysVector(new nostr.fb.RelayInfo.Vector()); }
  public nostr.fb.RelayInfo.Vector relaysVector(nostr.fb.RelayInfo.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKind10002Parsed(FlatBufferBuilder builder,
      int relaysOffset) {
    builder.startTable(1);
    Kind10002Parsed.addRelays(builder, relaysOffset);
    return Kind10002Parsed.endKind10002Parsed(builder);
  }

  public static void startKind10002Parsed(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addRelays(FlatBufferBuilder builder, int relaysOffset) { builder.addOffset(0, relaysOffset, 0); }
  public static int createRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKind10002Parsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // relays
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Kind10002Parsed get(int j) { return get(new Kind10002Parsed(), j); }
    public Kind10002Parsed get(Kind10002Parsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

