// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LightningData extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static LightningData getRootAsLightningData(ByteBuffer _bb) { return getRootAsLightningData(_bb, new LightningData()); }
  public static LightningData getRootAsLightningData(ByteBuffer _bb, LightningData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LightningData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String invoice() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer invoiceAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer invoiceInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createLightningData(FlatBufferBuilder builder,
      int invoiceOffset) {
    builder.startTable(1);
    LightningData.addInvoice(builder, invoiceOffset);
    return LightningData.endLightningData(builder);
  }

  public static void startLightningData(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addInvoice(FlatBufferBuilder builder, int invoiceOffset) { builder.addOffset(0, invoiceOffset, 0); }
  public static int endLightningData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // invoice
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LightningData get(int j) { return get(new LightningData(), j); }
    public LightningData get(LightningData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}
