// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ListParsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ListParsed getRootAsListParsed(ByteBuffer _bb) { return getRootAsListParsed(_bb, new ListParsed()); }
  public static ListParsed getRootAsListParsed(ByteBuffer _bb, ListParsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ListParsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int listKind() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public String d() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer dInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String title() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer titleAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer titleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String description() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String image() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer imageAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer imageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String topics(int j) { int o = __offset(14); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int topicsLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public StringVector topicsVector() { return topicsVector(new StringVector()); }
  public StringVector topicsVector(StringVector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String people(int j) { int o = __offset(16); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int peopleLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public StringVector peopleVector() { return peopleVector(new StringVector()); }
  public StringVector peopleVector(StringVector obj) { int o = __offset(16); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String events(int j) { int o = __offset(18); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int eventsLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public StringVector eventsVector() { return eventsVector(new StringVector()); }
  public StringVector eventsVector(StringVector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.Coordinate addresses(int j) { return addresses(new nostr.fb.Coordinate(), j); }
  public nostr.fb.Coordinate addresses(nostr.fb.Coordinate obj, int j) { int o = __offset(20); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int addressesLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.Coordinate.Vector addressesVector() { return addressesVector(new nostr.fb.Coordinate.Vector()); }
  public nostr.fb.Coordinate.Vector addressesVector(nostr.fb.Coordinate.Vector obj) { int o = __offset(20); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.Tag otherTags(int j) { return otherTags(new nostr.fb.Tag(), j); }
  public nostr.fb.Tag otherTags(nostr.fb.Tag obj, int j) { int o = __offset(22); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int otherTagsLength() { int o = __offset(22); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.Tag.Vector otherTagsVector() { return otherTagsVector(new nostr.fb.Tag.Vector()); }
  public nostr.fb.Tag.Vector otherTagsVector(nostr.fb.Tag.Vector obj) { int o = __offset(22); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createListParsed(FlatBufferBuilder builder,
      int listKind,
      int dOffset,
      int titleOffset,
      int descriptionOffset,
      int imageOffset,
      int topicsOffset,
      int peopleOffset,
      int eventsOffset,
      int addressesOffset,
      int otherTagsOffset) {
    builder.startTable(10);
    ListParsed.addOtherTags(builder, otherTagsOffset);
    ListParsed.addAddresses(builder, addressesOffset);
    ListParsed.addEvents(builder, eventsOffset);
    ListParsed.addPeople(builder, peopleOffset);
    ListParsed.addTopics(builder, topicsOffset);
    ListParsed.addImage(builder, imageOffset);
    ListParsed.addDescription(builder, descriptionOffset);
    ListParsed.addTitle(builder, titleOffset);
    ListParsed.addD(builder, dOffset);
    ListParsed.addListKind(builder, listKind);
    return ListParsed.endListParsed(builder);
  }

  public static void startListParsed(FlatBufferBuilder builder) { builder.startTable(10); }
  public static void addListKind(FlatBufferBuilder builder, int listKind) { builder.addShort(0, (short) listKind, (short) 0); }
  public static void addD(FlatBufferBuilder builder, int dOffset) { builder.addOffset(1, dOffset, 0); }
  public static void addTitle(FlatBufferBuilder builder, int titleOffset) { builder.addOffset(2, titleOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(3, descriptionOffset, 0); }
  public static void addImage(FlatBufferBuilder builder, int imageOffset) { builder.addOffset(4, imageOffset, 0); }
  public static void addTopics(FlatBufferBuilder builder, int topicsOffset) { builder.addOffset(5, topicsOffset, 0); }
  public static int createTopicsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTopicsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addPeople(FlatBufferBuilder builder, int peopleOffset) { builder.addOffset(6, peopleOffset, 0); }
  public static int createPeopleVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPeopleVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addEvents(FlatBufferBuilder builder, int eventsOffset) { builder.addOffset(7, eventsOffset, 0); }
  public static int createEventsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEventsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAddresses(FlatBufferBuilder builder, int addressesOffset) { builder.addOffset(8, addressesOffset, 0); }
  public static int createAddressesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAddressesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addOtherTags(FlatBufferBuilder builder, int otherTagsOffset) { builder.addOffset(9, otherTagsOffset, 0); }
  public static int createOtherTagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startOtherTagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endListParsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ListParsed get(int j) { return get(new ListParsed(), j); }
    public ListParsed get(ListParsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

