// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LiveActivityRef extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static LiveActivityRef getRootAsLiveActivityRef(ByteBuffer _bb) { return getRootAsLiveActivityRef(_bb, new LiveActivityRef()); }
  public static LiveActivityRef getRootAsLiveActivityRef(ByteBuffer _bb, LiveActivityRef obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LiveActivityRef __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int kind() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public String pubkey() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String identifier() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer identifierAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer identifierInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String relay() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer relayAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer relayInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createLiveActivityRef(FlatBufferBuilder builder,
      int kind,
      int pubkeyOffset,
      int identifierOffset,
      int relayOffset) {
    builder.startTable(4);
    LiveActivityRef.addRelay(builder, relayOffset);
    LiveActivityRef.addIdentifier(builder, identifierOffset);
    LiveActivityRef.addPubkey(builder, pubkeyOffset);
    LiveActivityRef.addKind(builder, kind);
    return LiveActivityRef.endLiveActivityRef(builder);
  }

  public static void startLiveActivityRef(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addKind(FlatBufferBuilder builder, int kind) { builder.addShort(0, (short) kind, (short) 0); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(1, pubkeyOffset, 0); }
  public static void addIdentifier(FlatBufferBuilder builder, int identifierOffset) { builder.addOffset(2, identifierOffset, 0); }
  public static void addRelay(FlatBufferBuilder builder, int relayOffset) { builder.addOffset(3, relayOffset, 0); }
  public static int endLiveActivityRef(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // pubkey
    builder.required(o, 8);  // identifier
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LiveActivityRef get(int j) { return get(new LiveActivityRef(), j); }
    public LiveActivityRef get(LiveActivityRef obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

