// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LiveChatThreadRef extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static LiveChatThreadRef getRootAsLiveChatThreadRef(ByteBuffer _bb) { return getRootAsLiveChatThreadRef(_bb, new LiveChatThreadRef()); }
  public static LiveChatThreadRef getRootAsLiveChatThreadRef(ByteBuffer _bb, LiveChatThreadRef obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LiveChatThreadRef __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String eventId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eventIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer eventIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String relay() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer relayAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer relayInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createLiveChatThreadRef(FlatBufferBuilder builder,
      int eventIdOffset,
      int relayOffset) {
    builder.startTable(2);
    LiveChatThreadRef.addRelay(builder, relayOffset);
    LiveChatThreadRef.addEventId(builder, eventIdOffset);
    return LiveChatThreadRef.endLiveChatThreadRef(builder);
  }

  public static void startLiveChatThreadRef(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addEventId(FlatBufferBuilder builder, int eventIdOffset) { builder.addOffset(0, eventIdOffset, 0); }
  public static void addRelay(FlatBufferBuilder builder, int relayOffset) { builder.addOffset(1, relayOffset, 0); }
  public static int endLiveChatThreadRef(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // event_id
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LiveChatThreadRef get(int j) { return get(new LiveChatThreadRef(), j); }
    public LiveChatThreadRef get(LiveChatThreadRef obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

