// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class MainContent {
  private MainContent() { }
  public static final byte NONE = 0;
  public static final byte Subscribe = 1;
  public static final byte Unsubscribe = 2;
  public static final byte Publish = 3;
  public static final byte SignEvent = 4;
  public static final byte SetSigner = 5;
  public static final byte GetPublicKey = 6;

  public static final String[] names = { "NONE", "Subscribe", "Unsubscribe", "Publish", "SignEvent", "SetSigner", "GetPublicKey", };

  public static String name(int e) { return names[e]; }
}

