// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MainMessage extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static MainMessage getRootAsMainMessage(ByteBuffer _bb) { return getRootAsMainMessage(_bb, new MainMessage()); }
  public static MainMessage getRootAsMainMessage(ByteBuffer _bb, MainMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MainMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte contentType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.google.flatbuffers.Table content(com.google.flatbuffers.Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createMainMessage(FlatBufferBuilder builder,
      byte contentType,
      int contentOffset) {
    builder.startTable(2);
    MainMessage.addContent(builder, contentOffset);
    MainMessage.addContentType(builder, contentType);
    return MainMessage.endMainMessage(builder);
  }

  public static void startMainMessage(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addContentType(FlatBufferBuilder builder, byte contentType) { builder.addByte(0, contentType, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(1, contentOffset, 0); }
  public static int endMainMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // content
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MainMessage get(int j) { return get(new MainMessage(), j); }
    public MainMessage get(MainMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

