// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MediaItem extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static MediaItem getRootAsMediaItem(ByteBuffer _bb) { return getRootAsMediaItem(_bb, new MediaItem()); }
  public static MediaItem getRootAsMediaItem(ByteBuffer _bb, MediaItem obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MediaItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public nostr.fb.ImageData image() { return image(new nostr.fb.ImageData()); }
  public nostr.fb.ImageData image(nostr.fb.ImageData obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public nostr.fb.VideoData video() { return video(new nostr.fb.VideoData()); }
  public nostr.fb.VideoData video(nostr.fb.VideoData obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createMediaItem(FlatBufferBuilder builder,
      int imageOffset,
      int videoOffset) {
    builder.startTable(2);
    MediaItem.addVideo(builder, videoOffset);
    MediaItem.addImage(builder, imageOffset);
    return MediaItem.endMediaItem(builder);
  }

  public static void startMediaItem(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addImage(FlatBufferBuilder builder, int imageOffset) { builder.addOffset(0, imageOffset, 0); }
  public static void addVideo(FlatBufferBuilder builder, int videoOffset) { builder.addOffset(1, videoOffset, 0); }
  public static int endMediaItem(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MediaItem get(int j) { return get(new MediaItem(), j); }
    public MediaItem get(MediaItem obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

