// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MediaGroupData extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static MediaGroupData getRootAsMediaGroupData(ByteBuffer _bb) { return getRootAsMediaGroupData(_bb, new MediaGroupData()); }
  public static MediaGroupData getRootAsMediaGroupData(ByteBuffer _bb, MediaGroupData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MediaGroupData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public nostr.fb.MediaItem items(int j) { return items(new nostr.fb.MediaItem(), j); }
  public nostr.fb.MediaItem items(nostr.fb.MediaItem obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int itemsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.MediaItem.Vector itemsVector() { return itemsVector(new nostr.fb.MediaItem.Vector()); }
  public nostr.fb.MediaItem.Vector itemsVector(nostr.fb.MediaItem.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createMediaGroupData(FlatBufferBuilder builder,
      int itemsOffset) {
    builder.startTable(1);
    MediaGroupData.addItems(builder, itemsOffset);
    return MediaGroupData.endMediaGroupData(builder);
  }

  public static void startMediaGroupData(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addItems(FlatBufferBuilder builder, int itemsOffset) { builder.addOffset(0, itemsOffset, 0); }
  public static int createItemsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startItemsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMediaGroupData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MediaGroupData get(int j) { return get(new MediaGroupData(), j); }
    public MediaGroupData get(MediaGroupData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

