// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class MessageType {
  private MessageType() { }
  public static final long ParsedNostrEvent = 0L;
  public static final long ConnectionStatus = 1L;
  public static final long CountResponse = 2L;
  public static final long Eoce = 3L;
  public static final long BufferFull = 4L;
  public static final long ValidProofs = 5L;
  public static final long SignedEvent = 6L;
  public static final long Pubkey = 7L;
  public static final long Raw = 8L;
  public static final long NostrEvent = 9L;
}

