// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class MessageType {
  private MessageType() { }
  public static final long ParsedNostrEvent = 0;
  public static final long ConnectionStatus = 1;
  public static final long CountResponse = 2;
  public static final long Eoce = 3;
  public static final long BufferFull = 4;
  public static final long ValidProofs = 5;
  public static final long SignedEvent = 6;
  public static final long Pubkey = 7;
  public static final long Raw = 8;
  public static final long NostrEvent = 9;
  public static final long SetSignerResponse = 10;
  public static final long AuthUrl = 11;
}

