// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class Message {
  private Message() { }
  public static final byte NONE = 0;
  public static final byte ParsedEvent = 1;
  public static final byte NostrEvent = 2;
  public static final byte ConnectionStatus = 3;
  public static final byte CountResponse = 4;
  public static final byte Eoce = 5;
  public static final byte BufferFull = 6;
  public static final byte ValidProofs = 7;
  public static final byte SignedEvent = 8;
  public static final byte Pubkey = 9;
  public static final byte Raw = 10;
  public static final byte SetSignerResponse = 11;

  public static final String[] names = { "NONE", "ParsedEvent", "NostrEvent", "ConnectionStatus", "CountResponse", "Eoce", "BufferFull", "ValidProofs", "SignedEvent", "Pubkey", "Raw", "SetSignerResponse", };

  public static String name(int e) { return names[e]; }
}

