// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MintProofs extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static MintProofs getRootAsMintProofs(ByteBuffer _bb) { return getRootAsMintProofs(_bb, new MintProofs()); }
  public static MintProofs getRootAsMintProofs(ByteBuffer _bb, MintProofs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MintProofs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String mint() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mintAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer mintInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public nostr.fb.Proof proofs(int j) { return proofs(new nostr.fb.Proof(), j); }
  public nostr.fb.Proof proofs(nostr.fb.Proof obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int proofsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.Proof.Vector proofsVector() { return proofsVector(new nostr.fb.Proof.Vector()); }
  public nostr.fb.Proof.Vector proofsVector(nostr.fb.Proof.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createMintProofs(FlatBufferBuilder builder,
      int mintOffset,
      int proofsOffset) {
    builder.startTable(2);
    MintProofs.addProofs(builder, proofsOffset);
    MintProofs.addMint(builder, mintOffset);
    return MintProofs.endMintProofs(builder);
  }

  public static void startMintProofs(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addMint(FlatBufferBuilder builder, int mintOffset) { builder.addOffset(0, mintOffset, 0); }
  public static void addProofs(FlatBufferBuilder builder, int proofsOffset) { builder.addOffset(1, proofsOffset, 0); }
  public static int createProofsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startProofsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMintProofs(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // mint
    builder.required(o, 6);  // proofs
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MintProofs get(int j) { return get(new MintProofs(), j); }
    public MintProofs get(MintProofs obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

