// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class MuteTarget {
  private MuteTarget() { }
  public static final byte Content = 0;
  public static final byte Tags = 1;
  public static final byte Both = 2;

  public static final String[] names = { "Content", "Tags", "Both", };

  public static String name(int e) { return names[e]; }
}

