// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MuteFilterPipeConfig extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static MuteFilterPipeConfig getRootAsMuteFilterPipeConfig(ByteBuffer _bb) { return getRootAsMuteFilterPipeConfig(_bb, new MuteFilterPipeConfig()); }
  public static MuteFilterPipeConfig getRootAsMuteFilterPipeConfig(ByteBuffer _bb, MuteFilterPipeConfig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MuteFilterPipeConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String pubkeys(int j) { int o = __offset(4); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int pubkeysLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public StringVector pubkeysVector() { return pubkeysVector(new StringVector()); }
  public StringVector pubkeysVector(StringVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String hashtags(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int hashtagsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public StringVector hashtagsVector() { return hashtagsVector(new StringVector()); }
  public StringVector hashtagsVector(StringVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String words(int j) { int o = __offset(8); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int wordsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public StringVector wordsVector() { return wordsVector(new StringVector()); }
  public StringVector wordsVector(StringVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String eventIds(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int eventIdsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public StringVector eventIdsVector() { return eventIdsVector(new StringVector()); }
  public StringVector eventIdsVector(StringVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public byte target() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 2; }

  public static int createMuteFilterPipeConfig(FlatBufferBuilder builder,
      int pubkeysOffset,
      int hashtagsOffset,
      int wordsOffset,
      int eventIdsOffset,
      byte target) {
    builder.startTable(5);
    MuteFilterPipeConfig.addEventIds(builder, eventIdsOffset);
    MuteFilterPipeConfig.addWords(builder, wordsOffset);
    MuteFilterPipeConfig.addHashtags(builder, hashtagsOffset);
    MuteFilterPipeConfig.addPubkeys(builder, pubkeysOffset);
    MuteFilterPipeConfig.addTarget(builder, target);
    return MuteFilterPipeConfig.endMuteFilterPipeConfig(builder);
  }

  public static void startMuteFilterPipeConfig(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addPubkeys(FlatBufferBuilder builder, int pubkeysOffset) { builder.addOffset(0, pubkeysOffset, 0); }
  public static int createPubkeysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPubkeysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addHashtags(FlatBufferBuilder builder, int hashtagsOffset) { builder.addOffset(1, hashtagsOffset, 0); }
  public static int createHashtagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startHashtagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addWords(FlatBufferBuilder builder, int wordsOffset) { builder.addOffset(2, wordsOffset, 0); }
  public static int createWordsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startWordsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addEventIds(FlatBufferBuilder builder, int eventIdsOffset) { builder.addOffset(3, eventIdsOffset, 0); }
  public static int createEventIdsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEventIdsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTarget(FlatBufferBuilder builder, byte target) { builder.addByte(4, target, 2); }
  public static int endMuteFilterPipeConfig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MuteFilterPipeConfig get(int j) { return get(new MuteFilterPipeConfig(), j); }
    public MuteFilterPipeConfig get(MuteFilterPipeConfig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

