// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Nip46Bunker extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Nip46Bunker getRootAsNip46Bunker(ByteBuffer _bb) { return getRootAsNip46Bunker(_bb, new Nip46Bunker()); }
  public static Nip46Bunker getRootAsNip46Bunker(ByteBuffer _bb, Nip46Bunker obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Nip46Bunker __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String bunkerUrl() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bunkerUrlAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer bunkerUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String clientSecret() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer clientSecretAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer clientSecretInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createNip46Bunker(FlatBufferBuilder builder,
      int bunkerUrlOffset,
      int clientSecretOffset) {
    builder.startTable(2);
    Nip46Bunker.addClientSecret(builder, clientSecretOffset);
    Nip46Bunker.addBunkerUrl(builder, bunkerUrlOffset);
    return Nip46Bunker.endNip46Bunker(builder);
  }

  public static void startNip46Bunker(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addBunkerUrl(FlatBufferBuilder builder, int bunkerUrlOffset) { builder.addOffset(0, bunkerUrlOffset, 0); }
  public static void addClientSecret(FlatBufferBuilder builder, int clientSecretOffset) { builder.addOffset(1, clientSecretOffset, 0); }
  public static int endNip46Bunker(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // bunker_url
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Nip46Bunker get(int j) { return get(new Nip46Bunker(), j); }
    public Nip46Bunker get(Nip46Bunker obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

