// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class NostrData extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static NostrData getRootAsNostrData(ByteBuffer _bb) { return getRootAsNostrData(_bb, new NostrData()); }
  public static NostrData getRootAsNostrData(ByteBuffer _bb, NostrData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public NostrData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String entity() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer entityAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer entityInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String relays(int j) { int o = __offset(8); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int relaysLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public StringVector relaysVector() { return relaysVector(new StringVector()); }
  public StringVector relaysVector(StringVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String author() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer authorAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer authorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public long kind() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createNostrData(FlatBufferBuilder builder,
      int idOffset,
      int entityOffset,
      int relaysOffset,
      int authorOffset,
      long kind) {
    builder.startTable(5);
    NostrData.addKind(builder, kind);
    NostrData.addAuthor(builder, authorOffset);
    NostrData.addRelays(builder, relaysOffset);
    NostrData.addEntity(builder, entityOffset);
    NostrData.addId(builder, idOffset);
    return NostrData.endNostrData(builder);
  }

  public static void startNostrData(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addEntity(FlatBufferBuilder builder, int entityOffset) { builder.addOffset(1, entityOffset, 0); }
  public static void addRelays(FlatBufferBuilder builder, int relaysOffset) { builder.addOffset(2, relaysOffset, 0); }
  public static int createRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAuthor(FlatBufferBuilder builder, int authorOffset) { builder.addOffset(3, authorOffset, 0); }
  public static void addKind(FlatBufferBuilder builder, long kind) { builder.addLong(4, kind, 0L); }
  public static int endNostrData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // id
    builder.required(o, 6);  // entity
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public NostrData get(int j) { return get(new NostrData(), j); }
    public NostrData get(NostrData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

