// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class NostrEvent extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static NostrEvent getRootAsNostrEvent(ByteBuffer _bb) { return getRootAsNostrEvent(_bb, new NostrEvent()); }
  public static NostrEvent getRootAsNostrEvent(ByteBuffer _bb, NostrEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public NostrEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String pubkey() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int kind() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public String content() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public nostr.fb.StringVec tags(int j) { return tags(new nostr.fb.StringVec(), j); }
  public nostr.fb.StringVec tags(nostr.fb.StringVec obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int tagsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.StringVec.Vector tagsVector() { return tagsVector(new nostr.fb.StringVec.Vector()); }
  public nostr.fb.StringVec.Vector tagsVector(nostr.fb.StringVec.Vector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public int createdAt() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String sig() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sigAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer sigInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }

  public static int createNostrEvent(FlatBufferBuilder builder,
      int idOffset,
      int pubkeyOffset,
      int kind,
      int contentOffset,
      int tagsOffset,
      int createdAt,
      int sigOffset) {
    builder.startTable(7);
    NostrEvent.addSig(builder, sigOffset);
    NostrEvent.addCreatedAt(builder, createdAt);
    NostrEvent.addTags(builder, tagsOffset);
    NostrEvent.addContent(builder, contentOffset);
    NostrEvent.addPubkey(builder, pubkeyOffset);
    NostrEvent.addId(builder, idOffset);
    NostrEvent.addKind(builder, kind);
    return NostrEvent.endNostrEvent(builder);
  }

  public static void startNostrEvent(FlatBufferBuilder builder) { builder.startTable(7); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(1, pubkeyOffset, 0); }
  public static void addKind(FlatBufferBuilder builder, int kind) { builder.addShort(2, (short) kind, (short) 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(3, contentOffset, 0); }
  public static void addTags(FlatBufferBuilder builder, int tagsOffset) { builder.addOffset(4, tagsOffset, 0); }
  public static int createTagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addCreatedAt(FlatBufferBuilder builder, int createdAt) { builder.addInt(5, createdAt, 0); }
  public static void addSig(FlatBufferBuilder builder, int sigOffset) { builder.addOffset(6, sigOffset, 0); }
  public static int endNostrEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // id
    builder.required(o, 6);  // pubkey
    builder.required(o, 10);  // content
    builder.required(o, 12);  // tags
    builder.required(o, 16);  // sig
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public NostrEvent get(int j) { return get(new NostrEvent(), j); }
    public NostrEvent get(NostrEvent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

