// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class NpubLimiterKey {
  private NpubLimiterKey() { }
  public static final int Author = 0;
  public static final int PTag = 1;

  public static final String[] names = { "Author", "PTag", };

  public static String name(int e) { return names[e]; }
}

