// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class NpubLimiterPipeConfig extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static NpubLimiterPipeConfig getRootAsNpubLimiterPipeConfig(ByteBuffer _bb) { return getRootAsNpubLimiterPipeConfig(_bb, new NpubLimiterPipeConfig()); }
  public static NpubLimiterPipeConfig getRootAsNpubLimiterPipeConfig(ByteBuffer _bb, NpubLimiterPipeConfig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public NpubLimiterPipeConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int kind() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public long limitPerNpub() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long maxTotalNpubs() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public int keyBy() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createNpubLimiterPipeConfig(FlatBufferBuilder builder,
      int kind,
      long limitPerNpub,
      long maxTotalNpubs,
      int keyBy) {
    builder.startTable(4);
    NpubLimiterPipeConfig.addMaxTotalNpubs(builder, maxTotalNpubs);
    NpubLimiterPipeConfig.addLimitPerNpub(builder, limitPerNpub);
    NpubLimiterPipeConfig.addKind(builder, kind);
    NpubLimiterPipeConfig.addKeyBy(builder, keyBy);
    return NpubLimiterPipeConfig.endNpubLimiterPipeConfig(builder);
  }

  public static void startNpubLimiterPipeConfig(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addKind(FlatBufferBuilder builder, int kind) { builder.addShort(0, (short) kind, (short) 0); }
  public static void addLimitPerNpub(FlatBufferBuilder builder, long limitPerNpub) { builder.addInt(1, (int) limitPerNpub, (int) 0L); }
  public static void addMaxTotalNpubs(FlatBufferBuilder builder, long maxTotalNpubs) { builder.addInt(2, (int) maxTotalNpubs, (int) 0L); }
  public static void addKeyBy(FlatBufferBuilder builder, int keyBy) { builder.addByte(3, (byte) keyBy, (byte) 0); }
  public static int endNpubLimiterPipeConfig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public NpubLimiterPipeConfig get(int j) { return get(new NpubLimiterPipeConfig(), j); }
    public NpubLimiterPipeConfig get(NpubLimiterPipeConfig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

