// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class P2PKWitness extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static P2PKWitness getRootAsP2PKWitness(ByteBuffer _bb) { return getRootAsP2PKWitness(_bb, new P2PKWitness()); }
  public static P2PKWitness getRootAsP2PKWitness(ByteBuffer _bb, P2PKWitness obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public P2PKWitness __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String signatures(int j) { int o = __offset(4); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int signaturesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public StringVector signaturesVector() { return signaturesVector(new StringVector()); }
  public StringVector signaturesVector(StringVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createP2PKWitness(FlatBufferBuilder builder,
      int signaturesOffset) {
    builder.startTable(1);
    P2PKWitness.addSignatures(builder, signaturesOffset);
    return P2PKWitness.endP2PKWitness(builder);
  }

  public static void startP2PKWitness(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addSignatures(FlatBufferBuilder builder, int signaturesOffset) { builder.addOffset(0, signaturesOffset, 0); }
  public static int createSignaturesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSignaturesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endP2PKWitness(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public P2PKWitness get(int j) { return get(new P2PKWitness(), j); }
    public P2PKWitness get(P2PKWitness obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

