// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class ParsedData {
  private ParsedData() { }
  public static final byte NONE = 0;
  public static final byte Kind0Parsed = 1;
  public static final byte Kind1Parsed = 2;
  public static final byte Kind3Parsed = 3;
  public static final byte Kind4Parsed = 4;
  public static final byte Kind6Parsed = 5;
  public static final byte Kind7Parsed = 6;
  public static final byte Kind8Parsed = 7;
  public static final byte Kind17Parsed = 8;
  public static final byte Kind20Parsed = 9;
  public static final byte Kind22Parsed = 10;
  public static final byte Kind1111Parsed = 11;
  public static final byte Kind1311Parsed = 12;
  public static final byte Kind1068Parsed = 13;
  public static final byte Kind1018Parsed = 14;
  public static final byte Kind10002Parsed = 15;
  public static final byte Kind10019Parsed = 16;
  public static final byte Kind17375Parsed = 17;
  public static final byte Kind7374Parsed = 18;
  public static final byte Kind7375Parsed = 19;
  public static final byte Kind7376Parsed = 20;
  public static final byte Kind9321Parsed = 21;
  public static final byte Kind9735Parsed = 22;
  public static final byte Kind30023Parsed = 23;
  public static final byte ListParsed = 24;
  public static final byte PreGenericParsed = 25;

  public static final String[] names = { "NONE", "Kind0Parsed", "Kind1Parsed", "Kind3Parsed", "Kind4Parsed", "Kind6Parsed", "Kind7Parsed", "Kind8Parsed", "Kind17Parsed", "Kind20Parsed", "Kind22Parsed", "Kind1111Parsed", "Kind1311Parsed", "Kind1068Parsed", "Kind1018Parsed", "Kind10002Parsed", "Kind10019Parsed", "Kind17375Parsed", "Kind7374Parsed", "Kind7375Parsed", "Kind7376Parsed", "Kind9321Parsed", "Kind9735Parsed", "Kind30023Parsed", "ListParsed", "PreGenericParsed", };

  public static String name(int e) { return names[e]; }
}

