// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ParsePipeConfig extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ParsePipeConfig getRootAsParsePipeConfig(ByteBuffer _bb) { return getRootAsParsePipeConfig(_bb, new ParsePipeConfig()); }
  public static ParsePipeConfig getRootAsParsePipeConfig(ByteBuffer _bb, ParsePipeConfig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ParsePipeConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startParsePipeConfig(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endParsePipeConfig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ParsePipeConfig get(int j) { return get(new ParsePipeConfig(), j); }
    public ParsePipeConfig get(ParsePipeConfig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

