// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ParsedEvent extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ParsedEvent getRootAsParsedEvent(ByteBuffer _bb) { return getRootAsParsedEvent(_bb, new ParsedEvent()); }
  public static ParsedEvent getRootAsParsedEvent(ByteBuffer _bb, ParsedEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ParsedEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String pubkey() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int kind() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public long createdAt() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public byte parsedType() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.google.flatbuffers.Table parsed(com.google.flatbuffers.Table obj) { int o = __offset(14); return o != 0 ? __union(obj, o + bb_pos) : null; }
  public nostr.fb.Request requests(int j) { return requests(new nostr.fb.Request(), j); }
  public nostr.fb.Request requests(nostr.fb.Request obj, int j) { int o = __offset(16); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int requestsLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.Request.Vector requestsVector() { return requestsVector(new nostr.fb.Request.Vector()); }
  public nostr.fb.Request.Vector requestsVector(nostr.fb.Request.Vector obj) { int o = __offset(16); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String relays(int j) { int o = __offset(18); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int relaysLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public StringVector relaysVector() { return relaysVector(new StringVector()); }
  public StringVector relaysVector(StringVector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.StringVec tags(int j) { return tags(new nostr.fb.StringVec(), j); }
  public nostr.fb.StringVec tags(nostr.fb.StringVec obj, int j) { int o = __offset(20); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int tagsLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.StringVec.Vector tagsVector() { return tagsVector(new nostr.fb.StringVec.Vector()); }
  public nostr.fb.StringVec.Vector tagsVector(nostr.fb.StringVec.Vector obj) { int o = __offset(20); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createParsedEvent(FlatBufferBuilder builder,
      int idOffset,
      int pubkeyOffset,
      int kind,
      long createdAt,
      byte parsedType,
      int parsedOffset,
      int requestsOffset,
      int relaysOffset,
      int tagsOffset) {
    builder.startTable(9);
    ParsedEvent.addTags(builder, tagsOffset);
    ParsedEvent.addRelays(builder, relaysOffset);
    ParsedEvent.addRequests(builder, requestsOffset);
    ParsedEvent.addParsed(builder, parsedOffset);
    ParsedEvent.addCreatedAt(builder, createdAt);
    ParsedEvent.addPubkey(builder, pubkeyOffset);
    ParsedEvent.addId(builder, idOffset);
    ParsedEvent.addKind(builder, kind);
    ParsedEvent.addParsedType(builder, parsedType);
    return ParsedEvent.endParsedEvent(builder);
  }

  public static void startParsedEvent(FlatBufferBuilder builder) { builder.startTable(9); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(1, pubkeyOffset, 0); }
  public static void addKind(FlatBufferBuilder builder, int kind) { builder.addShort(2, (short) kind, (short) 0); }
  public static void addCreatedAt(FlatBufferBuilder builder, long createdAt) { builder.addInt(3, (int) createdAt, (int) 0L); }
  public static void addParsedType(FlatBufferBuilder builder, byte parsedType) { builder.addByte(4, parsedType, 0); }
  public static void addParsed(FlatBufferBuilder builder, int parsedOffset) { builder.addOffset(5, parsedOffset, 0); }
  public static void addRequests(FlatBufferBuilder builder, int requestsOffset) { builder.addOffset(6, requestsOffset, 0); }
  public static int createRequestsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRequestsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRelays(FlatBufferBuilder builder, int relaysOffset) { builder.addOffset(7, relaysOffset, 0); }
  public static int createRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTags(FlatBufferBuilder builder, int tagsOffset) { builder.addOffset(8, tagsOffset, 0); }
  public static int createTagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endParsedEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // id
    builder.required(o, 6);  // pubkey
    builder.required(o, 20);  // tags
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ParsedEvent get(int j) { return get(new ParsedEvent(), j); }
    public ParsedEvent get(ParsedEvent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

