// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Pipe extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Pipe getRootAsPipe(ByteBuffer _bb) { return getRootAsPipe(_bb, new Pipe()); }
  public static Pipe getRootAsPipe(ByteBuffer _bb, Pipe obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Pipe __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte configType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.google.flatbuffers.Table config(com.google.flatbuffers.Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createPipe(FlatBufferBuilder builder,
      byte configType,
      int configOffset) {
    builder.startTable(2);
    Pipe.addConfig(builder, configOffset);
    Pipe.addConfigType(builder, configType);
    return Pipe.endPipe(builder);
  }

  public static void startPipe(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addConfigType(FlatBufferBuilder builder, byte configType) { builder.addByte(0, configType, 0); }
  public static void addConfig(FlatBufferBuilder builder, int configOffset) { builder.addOffset(1, configOffset, 0); }
  public static int endPipe(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // config
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Pipe get(int j) { return get(new Pipe(), j); }
    public Pipe get(Pipe obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

