// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PipelineConfig extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static PipelineConfig getRootAsPipelineConfig(ByteBuffer _bb) { return getRootAsPipelineConfig(_bb, new PipelineConfig()); }
  public static PipelineConfig getRootAsPipelineConfig(ByteBuffer _bb, PipelineConfig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PipelineConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public nostr.fb.Pipe pipes(int j) { return pipes(new nostr.fb.Pipe(), j); }
  public nostr.fb.Pipe pipes(nostr.fb.Pipe obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int pipesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.Pipe.Vector pipesVector() { return pipesVector(new nostr.fb.Pipe.Vector()); }
  public nostr.fb.Pipe.Vector pipesVector(nostr.fb.Pipe.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createPipelineConfig(FlatBufferBuilder builder,
      int pipesOffset) {
    builder.startTable(1);
    PipelineConfig.addPipes(builder, pipesOffset);
    return PipelineConfig.endPipelineConfig(builder);
  }

  public static void startPipelineConfig(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addPipes(FlatBufferBuilder builder, int pipesOffset) { builder.addOffset(0, pipesOffset, 0); }
  public static int createPipesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPipesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endPipelineConfig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // pipes
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PipelineConfig get(int j) { return get(new PipelineConfig(), j); }
    public PipelineConfig get(PipelineConfig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

