// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class PipeConfig {
  private PipeConfig() { }
  public static final byte NONE = 0;
  public static final byte ParsePipeConfig = 1;
  public static final byte KindFilterPipeConfig = 2;
  public static final byte CounterPipeConfig = 3;
  public static final byte NpubLimiterPipeConfig = 4;
  public static final byte ChatLimiterPipeConfig = 5;
  public static final byte SaveToDbPipeConfig = 6;
  public static final byte SerializeEventsPipeConfig = 7;
  public static final byte ProofVerificationPipeConfig = 8;
  public static final byte MuteFilterPipeConfig = 9;

  public static final String[] names = { "NONE", "ParsePipeConfig", "KindFilterPipeConfig", "CounterPipeConfig", "NpubLimiterPipeConfig", "ChatLimiterPipeConfig", "SaveToDbPipeConfig", "SerializeEventsPipeConfig", "ProofVerificationPipeConfig", "MuteFilterPipeConfig", };

  public static String name(int e) { return names[e]; }
}

