// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class PollType {
  private PollType() { }
  public static final byte SingleChoice = 0;
  public static final byte MultipleChoice = 1;

  public static final String[] names = { "SingleChoice", "MultipleChoice", };

  public static String name(int e) { return names[e]; }
}

