// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PreGenericParsed extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static PreGenericParsed getRootAsPreGenericParsed(ByteBuffer _bb) { return getRootAsPreGenericParsed(_bb, new PreGenericParsed()); }
  public static PreGenericParsed getRootAsPreGenericParsed(ByteBuffer _bb, PreGenericParsed obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PreGenericParsed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int kind() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public String d() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer dInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String content() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String title() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer titleAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer titleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String description() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String image() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer imageAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer imageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String streaming() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer streamingAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer streamingInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public String recording() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer recordingAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer recordingInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public String service() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer serviceAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer serviceInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public String endpoint() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer endpointAsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public ByteBuffer endpointInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 22, 1); }
  public String room() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public ByteBuffer roomInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 1); }
  public String status() { int o = __offset(26); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer statusAsByteBuffer() { return __vector_as_bytebuffer(26, 1); }
  public ByteBuffer statusInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 26, 1); }
  public long starts() { int o = __offset(28); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long ends() { int o = __offset(30); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String location() { int o = __offset(32); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer locationAsByteBuffer() { return __vector_as_bytebuffer(32, 1); }
  public ByteBuffer locationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 32, 1); }
  public long currentParticipants() { int o = __offset(34); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long totalParticipants() { int o = __offset(36); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String pinned() { int o = __offset(38); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pinnedAsByteBuffer() { return __vector_as_bytebuffer(38, 1); }
  public ByteBuffer pinnedInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 38, 1); }
  public String topics(int j) { int o = __offset(40); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int topicsLength() { int o = __offset(40); return o != 0 ? __vector_len(o) : 0; }
  public StringVector topicsVector() { return topicsVector(new StringVector()); }
  public StringVector topicsVector(StringVector obj) { int o = __offset(40); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String links(int j) { int o = __offset(42); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int linksLength() { int o = __offset(42); return o != 0 ? __vector_len(o) : 0; }
  public StringVector linksVector() { return linksVector(new StringVector()); }
  public StringVector linksVector(StringVector obj) { int o = __offset(42); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String relays(int j) { int o = __offset(44); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int relaysLength() { int o = __offset(44); return o != 0 ? __vector_len(o) : 0; }
  public StringVector relaysVector() { return relaysVector(new StringVector()); }
  public StringVector relaysVector(StringVector obj) { int o = __offset(44); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.PreParticipant participants(int j) { return participants(new nostr.fb.PreParticipant(), j); }
  public nostr.fb.PreParticipant participants(nostr.fb.PreParticipant obj, int j) { int o = __offset(46); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int participantsLength() { int o = __offset(46); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.PreParticipant.Vector participantsVector() { return participantsVector(new nostr.fb.PreParticipant.Vector()); }
  public nostr.fb.PreParticipant.Vector participantsVector(nostr.fb.PreParticipant.Vector obj) { int o = __offset(46); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.PreRefEvent events(int j) { return events(new nostr.fb.PreRefEvent(), j); }
  public nostr.fb.PreRefEvent events(nostr.fb.PreRefEvent obj, int j) { int o = __offset(48); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int eventsLength() { int o = __offset(48); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.PreRefEvent.Vector eventsVector() { return eventsVector(new nostr.fb.PreRefEvent.Vector()); }
  public nostr.fb.PreRefEvent.Vector eventsVector(nostr.fb.PreRefEvent.Vector obj) { int o = __offset(48); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.Coordinate addresses(int j) { return addresses(new nostr.fb.Coordinate(), j); }
  public nostr.fb.Coordinate addresses(nostr.fb.Coordinate obj, int j) { int o = __offset(50); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int addressesLength() { int o = __offset(50); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.Coordinate.Vector addressesVector() { return addressesVector(new nostr.fb.Coordinate.Vector()); }
  public nostr.fb.Coordinate.Vector addressesVector(nostr.fb.Coordinate.Vector obj) { int o = __offset(50); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.StringVec tags(int j) { return tags(new nostr.fb.StringVec(), j); }
  public nostr.fb.StringVec tags(nostr.fb.StringVec obj, int j) { int o = __offset(52); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int tagsLength() { int o = __offset(52); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.StringVec.Vector tagsVector() { return tagsVector(new nostr.fb.StringVec.Vector()); }
  public nostr.fb.StringVec.Vector tagsVector(nostr.fb.StringVec.Vector obj) { int o = __offset(52); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createPreGenericParsed(FlatBufferBuilder builder,
      int kind,
      int dOffset,
      int contentOffset,
      int titleOffset,
      int descriptionOffset,
      int imageOffset,
      int streamingOffset,
      int recordingOffset,
      int serviceOffset,
      int endpointOffset,
      int roomOffset,
      int statusOffset,
      long starts,
      long ends,
      int locationOffset,
      long currentParticipants,
      long totalParticipants,
      int pinnedOffset,
      int topicsOffset,
      int linksOffset,
      int relaysOffset,
      int participantsOffset,
      int eventsOffset,
      int addressesOffset,
      int tagsOffset) {
    builder.startTable(25);
    PreGenericParsed.addTotalParticipants(builder, totalParticipants);
    PreGenericParsed.addCurrentParticipants(builder, currentParticipants);
    PreGenericParsed.addEnds(builder, ends);
    PreGenericParsed.addStarts(builder, starts);
    PreGenericParsed.addTags(builder, tagsOffset);
    PreGenericParsed.addAddresses(builder, addressesOffset);
    PreGenericParsed.addEvents(builder, eventsOffset);
    PreGenericParsed.addParticipants(builder, participantsOffset);
    PreGenericParsed.addRelays(builder, relaysOffset);
    PreGenericParsed.addLinks(builder, linksOffset);
    PreGenericParsed.addTopics(builder, topicsOffset);
    PreGenericParsed.addPinned(builder, pinnedOffset);
    PreGenericParsed.addLocation(builder, locationOffset);
    PreGenericParsed.addStatus(builder, statusOffset);
    PreGenericParsed.addRoom(builder, roomOffset);
    PreGenericParsed.addEndpoint(builder, endpointOffset);
    PreGenericParsed.addService(builder, serviceOffset);
    PreGenericParsed.addRecording(builder, recordingOffset);
    PreGenericParsed.addStreaming(builder, streamingOffset);
    PreGenericParsed.addImage(builder, imageOffset);
    PreGenericParsed.addDescription(builder, descriptionOffset);
    PreGenericParsed.addTitle(builder, titleOffset);
    PreGenericParsed.addContent(builder, contentOffset);
    PreGenericParsed.addD(builder, dOffset);
    PreGenericParsed.addKind(builder, kind);
    return PreGenericParsed.endPreGenericParsed(builder);
  }

  public static void startPreGenericParsed(FlatBufferBuilder builder) { builder.startTable(25); }
  public static void addKind(FlatBufferBuilder builder, int kind) { builder.addShort(0, (short) kind, (short) 0); }
  public static void addD(FlatBufferBuilder builder, int dOffset) { builder.addOffset(1, dOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(2, contentOffset, 0); }
  public static void addTitle(FlatBufferBuilder builder, int titleOffset) { builder.addOffset(3, titleOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(4, descriptionOffset, 0); }
  public static void addImage(FlatBufferBuilder builder, int imageOffset) { builder.addOffset(5, imageOffset, 0); }
  public static void addStreaming(FlatBufferBuilder builder, int streamingOffset) { builder.addOffset(6, streamingOffset, 0); }
  public static void addRecording(FlatBufferBuilder builder, int recordingOffset) { builder.addOffset(7, recordingOffset, 0); }
  public static void addService(FlatBufferBuilder builder, int serviceOffset) { builder.addOffset(8, serviceOffset, 0); }
  public static void addEndpoint(FlatBufferBuilder builder, int endpointOffset) { builder.addOffset(9, endpointOffset, 0); }
  public static void addRoom(FlatBufferBuilder builder, int roomOffset) { builder.addOffset(10, roomOffset, 0); }
  public static void addStatus(FlatBufferBuilder builder, int statusOffset) { builder.addOffset(11, statusOffset, 0); }
  public static void addStarts(FlatBufferBuilder builder, long starts) { builder.addLong(12, starts, 0L); }
  public static void addEnds(FlatBufferBuilder builder, long ends) { builder.addLong(13, ends, 0L); }
  public static void addLocation(FlatBufferBuilder builder, int locationOffset) { builder.addOffset(14, locationOffset, 0); }
  public static void addCurrentParticipants(FlatBufferBuilder builder, long currentParticipants) { builder.addLong(15, currentParticipants, 0L); }
  public static void addTotalParticipants(FlatBufferBuilder builder, long totalParticipants) { builder.addLong(16, totalParticipants, 0L); }
  public static void addPinned(FlatBufferBuilder builder, int pinnedOffset) { builder.addOffset(17, pinnedOffset, 0); }
  public static void addTopics(FlatBufferBuilder builder, int topicsOffset) { builder.addOffset(18, topicsOffset, 0); }
  public static int createTopicsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTopicsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addLinks(FlatBufferBuilder builder, int linksOffset) { builder.addOffset(19, linksOffset, 0); }
  public static int createLinksVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startLinksVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRelays(FlatBufferBuilder builder, int relaysOffset) { builder.addOffset(20, relaysOffset, 0); }
  public static int createRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addParticipants(FlatBufferBuilder builder, int participantsOffset) { builder.addOffset(21, participantsOffset, 0); }
  public static int createParticipantsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startParticipantsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addEvents(FlatBufferBuilder builder, int eventsOffset) { builder.addOffset(22, eventsOffset, 0); }
  public static int createEventsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEventsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAddresses(FlatBufferBuilder builder, int addressesOffset) { builder.addOffset(23, addressesOffset, 0); }
  public static int createAddressesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAddressesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTags(FlatBufferBuilder builder, int tagsOffset) { builder.addOffset(24, tagsOffset, 0); }
  public static int createTagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endPreGenericParsed(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PreGenericParsed get(int j) { return get(new PreGenericParsed(), j); }
    public PreGenericParsed get(PreGenericParsed obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

