// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PreParticipant extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static PreParticipant getRootAsPreParticipant(ByteBuffer _bb) { return getRootAsPreParticipant(_bb, new PreParticipant()); }
  public static PreParticipant getRootAsPreParticipant(ByteBuffer _bb, PreParticipant obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PreParticipant __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String pubkey() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String relay() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer relayAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer relayInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String role() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roleAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer roleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String proof() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer proofAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer proofInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createPreParticipant(FlatBufferBuilder builder,
      int pubkeyOffset,
      int relayOffset,
      int roleOffset,
      int proofOffset) {
    builder.startTable(4);
    PreParticipant.addProof(builder, proofOffset);
    PreParticipant.addRole(builder, roleOffset);
    PreParticipant.addRelay(builder, relayOffset);
    PreParticipant.addPubkey(builder, pubkeyOffset);
    return PreParticipant.endPreParticipant(builder);
  }

  public static void startPreParticipant(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(0, pubkeyOffset, 0); }
  public static void addRelay(FlatBufferBuilder builder, int relayOffset) { builder.addOffset(1, relayOffset, 0); }
  public static void addRole(FlatBufferBuilder builder, int roleOffset) { builder.addOffset(2, roleOffset, 0); }
  public static void addProof(FlatBufferBuilder builder, int proofOffset) { builder.addOffset(3, proofOffset, 0); }
  public static int endPreParticipant(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // pubkey
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PreParticipant get(int j) { return get(new PreParticipant(), j); }
    public PreParticipant get(PreParticipant obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

