// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ProfilePointer extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ProfilePointer getRootAsProfilePointer(ByteBuffer _bb) { return getRootAsProfilePointer(_bb, new ProfilePointer()); }
  public static ProfilePointer getRootAsProfilePointer(ByteBuffer _bb, ProfilePointer obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ProfilePointer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String publicKey() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer publicKeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer publicKeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String relays(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int relaysLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public StringVector relaysVector() { return relaysVector(new StringVector()); }
  public StringVector relaysVector(StringVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createProfilePointer(FlatBufferBuilder builder,
      int publicKeyOffset,
      int relaysOffset) {
    builder.startTable(2);
    ProfilePointer.addRelays(builder, relaysOffset);
    ProfilePointer.addPublicKey(builder, publicKeyOffset);
    return ProfilePointer.endProfilePointer(builder);
  }

  public static void startProfilePointer(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addPublicKey(FlatBufferBuilder builder, int publicKeyOffset) { builder.addOffset(0, publicKeyOffset, 0); }
  public static void addRelays(FlatBufferBuilder builder, int relaysOffset) { builder.addOffset(1, relaysOffset, 0); }
  public static int createRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endProfilePointer(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // public_key
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ProfilePointer get(int j) { return get(new ProfilePointer(), j); }
    public ProfilePointer get(ProfilePointer obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

