// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Proof extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Proof getRootAsProof(ByteBuffer _bb) { return getRootAsProof(_bb, new Proof()); }
  public static Proof getRootAsProof(ByteBuffer _bb, Proof obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Proof __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long amount() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String id() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String secret() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer secretAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer secretInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String c() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer cAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer cInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public nostr.fb.DLEQProof dleq() { return dleq(new nostr.fb.DLEQProof()); }
  public nostr.fb.DLEQProof dleq(nostr.fb.DLEQProof obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public byte witnessType() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.google.flatbuffers.Table witness(com.google.flatbuffers.Table obj) { int o = __offset(16); return o != 0 ? __union(obj, o + bb_pos) : null; }
  public int version() { int o = __offset(18); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createProof(FlatBufferBuilder builder,
      long amount,
      int idOffset,
      int secretOffset,
      int cOffset,
      int dleqOffset,
      byte witnessType,
      int witnessOffset,
      int version) {
    builder.startTable(8);
    Proof.addAmount(builder, amount);
    Proof.addWitness(builder, witnessOffset);
    Proof.addDleq(builder, dleqOffset);
    Proof.addC(builder, cOffset);
    Proof.addSecret(builder, secretOffset);
    Proof.addId(builder, idOffset);
    Proof.addVersion(builder, version);
    Proof.addWitnessType(builder, witnessType);
    return Proof.endProof(builder);
  }

  public static void startProof(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addAmount(FlatBufferBuilder builder, long amount) { builder.addLong(0, amount, 0L); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(1, idOffset, 0); }
  public static void addSecret(FlatBufferBuilder builder, int secretOffset) { builder.addOffset(2, secretOffset, 0); }
  public static void addC(FlatBufferBuilder builder, int cOffset) { builder.addOffset(3, cOffset, 0); }
  public static void addDleq(FlatBufferBuilder builder, int dleqOffset) { builder.addOffset(4, dleqOffset, 0); }
  public static void addWitnessType(FlatBufferBuilder builder, byte witnessType) { builder.addByte(5, witnessType, 0); }
  public static void addWitness(FlatBufferBuilder builder, int witnessOffset) { builder.addOffset(6, witnessOffset, 0); }
  public static void addVersion(FlatBufferBuilder builder, int version) { builder.addByte(7, (byte) version, (byte) 0); }
  public static int endProof(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // id
    builder.required(o, 8);  // secret
    builder.required(o, 10);  // c
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Proof get(int j) { return get(new Proof(), j); }
    public Proof get(Proof obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

