// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ProofVerificationPipeConfig extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ProofVerificationPipeConfig getRootAsProofVerificationPipeConfig(ByteBuffer _bb) { return getRootAsProofVerificationPipeConfig(_bb, new ProofVerificationPipeConfig()); }
  public static ProofVerificationPipeConfig getRootAsProofVerificationPipeConfig(ByteBuffer _bb, ProofVerificationPipeConfig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ProofVerificationPipeConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long maxProofs() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createProofVerificationPipeConfig(FlatBufferBuilder builder,
      long maxProofs) {
    builder.startTable(1);
    ProofVerificationPipeConfig.addMaxProofs(builder, maxProofs);
    return ProofVerificationPipeConfig.endProofVerificationPipeConfig(builder);
  }

  public static void startProofVerificationPipeConfig(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMaxProofs(FlatBufferBuilder builder, long maxProofs) { builder.addInt(0, (int) maxProofs, (int) 0L); }
  public static int endProofVerificationPipeConfig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ProofVerificationPipeConfig get(int j) { return get(new ProofVerificationPipeConfig(), j); }
    public ProofVerificationPipeConfig get(ProofVerificationPipeConfig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

