// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Publish extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Publish getRootAsPublish(ByteBuffer _bb) { return getRootAsPublish(_bb, new Publish()); }
  public static Publish getRootAsPublish(ByteBuffer _bb, Publish obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Publish __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String publishId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer publishIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer publishIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public nostr.fb.Template template() { return template(new nostr.fb.Template()); }
  public nostr.fb.Template template(nostr.fb.Template obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String relays(int j) { int o = __offset(8); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int relaysLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public StringVector relaysVector() { return relaysVector(new StringVector()); }
  public StringVector relaysVector(StringVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String optimisticSubids(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int optimisticSubidsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public StringVector optimisticSubidsVector() { return optimisticSubidsVector(new StringVector()); }
  public StringVector optimisticSubidsVector(StringVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createPublish(FlatBufferBuilder builder,
      int publishIdOffset,
      int templateOffset,
      int relaysOffset,
      int optimisticSubidsOffset) {
    builder.startTable(4);
    Publish.addOptimisticSubids(builder, optimisticSubidsOffset);
    Publish.addRelays(builder, relaysOffset);
    Publish.addTemplate(builder, templateOffset);
    Publish.addPublishId(builder, publishIdOffset);
    return Publish.endPublish(builder);
  }

  public static void startPublish(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addPublishId(FlatBufferBuilder builder, int publishIdOffset) { builder.addOffset(0, publishIdOffset, 0); }
  public static void addTemplate(FlatBufferBuilder builder, int templateOffset) { builder.addOffset(1, templateOffset, 0); }
  public static void addRelays(FlatBufferBuilder builder, int relaysOffset) { builder.addOffset(2, relaysOffset, 0); }
  public static int createRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addOptimisticSubids(FlatBufferBuilder builder, int optimisticSubidsOffset) { builder.addOffset(3, optimisticSubidsOffset, 0); }
  public static int createOptimisticSubidsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startOptimisticSubidsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endPublish(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // publish_id
    builder.required(o, 6);  // template
    builder.required(o, 8);  // relays
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Publish get(int j) { return get(new Publish(), j); }
    public Publish get(Publish obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

