// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Raw extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Raw getRootAsRaw(ByteBuffer _bb) { return getRootAsRaw(_bb, new Raw()); }
  public static Raw getRootAsRaw(ByteBuffer _bb, Raw obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Raw __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String raw() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer rawAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer rawInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createRaw(FlatBufferBuilder builder,
      int rawOffset) {
    builder.startTable(1);
    Raw.addRaw(builder, rawOffset);
    return Raw.endRaw(builder);
  }

  public static void startRaw(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addRaw(FlatBufferBuilder builder, int rawOffset) { builder.addOffset(0, rawOffset, 0); }
  public static int endRaw(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // raw
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Raw get(int j) { return get(new Raw(), j); }
    public Raw get(Raw obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

