// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class ReactionType {
  private ReactionType() { }
  public static final byte Like = 0;
  public static final byte Dislike = 1;
  public static final byte Emoji = 2;
  public static final byte Custom = 3;

  public static final String[] names = { "Like", "Dislike", "Emoji", "Custom", };

  public static String name(int e) { return names[e]; }
}

