// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RelayInfo extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static RelayInfo getRootAsRelayInfo(ByteBuffer _bb) { return getRootAsRelayInfo(_bb, new RelayInfo()); }
  public static RelayInfo getRootAsRelayInfo(ByteBuffer _bb, RelayInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RelayInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String url() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public boolean read() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean write() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createRelayInfo(FlatBufferBuilder builder,
      int urlOffset,
      boolean read,
      boolean write) {
    builder.startTable(3);
    RelayInfo.addUrl(builder, urlOffset);
    RelayInfo.addWrite(builder, write);
    RelayInfo.addRead(builder, read);
    return RelayInfo.endRelayInfo(builder);
  }

  public static void startRelayInfo(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(0, urlOffset, 0); }
  public static void addRead(FlatBufferBuilder builder, boolean read) { builder.addBoolean(1, read, false); }
  public static void addWrite(FlatBufferBuilder builder, boolean write) { builder.addBoolean(2, write, false); }
  public static int endRelayInfo(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // url
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RelayInfo get(int j) { return get(new RelayInfo(), j); }
    public RelayInfo get(RelayInfo obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

