// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Request extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Request getRootAsRequest(ByteBuffer _bb) { return getRootAsRequest(_bb, new Request()); }
  public static Request getRootAsRequest(ByteBuffer _bb, Request obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Request __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String ids(int j) { int o = __offset(4); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int idsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public StringVector idsVector() { return idsVector(new StringVector()); }
  public StringVector idsVector(StringVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String authors(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int authorsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public StringVector authorsVector() { return authorsVector(new StringVector()); }
  public StringVector authorsVector(StringVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public int kinds(int j) { int o = __offset(8); return o != 0 ? bb.getShort(__vector(o) + j * 2) & 0xFFFF : 0; }
  public int kindsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ShortVector kindsVector() { return kindsVector(new ShortVector()); }
  public ShortVector kindsVector(ShortVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer kindsAsByteBuffer() { return __vector_as_bytebuffer(8, 2); }
  public ByteBuffer kindsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 2); }
  public nostr.fb.StringVec tags(int j) { return tags(new nostr.fb.StringVec(), j); }
  public nostr.fb.StringVec tags(nostr.fb.StringVec obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int tagsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.StringVec.Vector tagsVector() { return tagsVector(new nostr.fb.StringVec.Vector()); }
  public nostr.fb.StringVec.Vector tagsVector(nostr.fb.StringVec.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public int limit() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int since() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int until() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String search() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer searchAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer searchInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public String relays(int j) { int o = __offset(20); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int relaysLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public StringVector relaysVector() { return relaysVector(new StringVector()); }
  public StringVector relaysVector(StringVector obj) { int o = __offset(20); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public boolean closeOnEose() { int o = __offset(22); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean cacheFirst() { int o = __offset(24); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean noCache() { int o = __offset(26); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int maxRelays() { int o = __offset(28); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean cacheOnly() { int o = __offset(30); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createRequest(FlatBufferBuilder builder,
      int idsOffset,
      int authorsOffset,
      int kindsOffset,
      int tagsOffset,
      int limit,
      int since,
      int until,
      int searchOffset,
      int relaysOffset,
      boolean closeOnEose,
      boolean cacheFirst,
      boolean noCache,
      int maxRelays,
      boolean cacheOnly) {
    builder.startTable(14);
    Request.addRelays(builder, relaysOffset);
    Request.addSearch(builder, searchOffset);
    Request.addUntil(builder, until);
    Request.addSince(builder, since);
    Request.addLimit(builder, limit);
    Request.addTags(builder, tagsOffset);
    Request.addKinds(builder, kindsOffset);
    Request.addAuthors(builder, authorsOffset);
    Request.addIds(builder, idsOffset);
    Request.addMaxRelays(builder, maxRelays);
    Request.addCacheOnly(builder, cacheOnly);
    Request.addNoCache(builder, noCache);
    Request.addCacheFirst(builder, cacheFirst);
    Request.addCloseOnEose(builder, closeOnEose);
    return Request.endRequest(builder);
  }

  public static void startRequest(FlatBufferBuilder builder) { builder.startTable(14); }
  public static void addIds(FlatBufferBuilder builder, int idsOffset) { builder.addOffset(0, idsOffset, 0); }
  public static int createIdsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startIdsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAuthors(FlatBufferBuilder builder, int authorsOffset) { builder.addOffset(1, authorsOffset, 0); }
  public static int createAuthorsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAuthorsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addKinds(FlatBufferBuilder builder, int kindsOffset) { builder.addOffset(2, kindsOffset, 0); }
  public static int createKindsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort((short) data[i]); return builder.endVector(); }
  public static void startKindsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static void addTags(FlatBufferBuilder builder, int tagsOffset) { builder.addOffset(3, tagsOffset, 0); }
  public static int createTagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addLimit(FlatBufferBuilder builder, int limit) { builder.addInt(4, limit, 0); }
  public static void addSince(FlatBufferBuilder builder, int since) { builder.addInt(5, since, 0); }
  public static void addUntil(FlatBufferBuilder builder, int until) { builder.addInt(6, until, 0); }
  public static void addSearch(FlatBufferBuilder builder, int searchOffset) { builder.addOffset(7, searchOffset, 0); }
  public static void addRelays(FlatBufferBuilder builder, int relaysOffset) { builder.addOffset(8, relaysOffset, 0); }
  public static int createRelaysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRelaysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addCloseOnEose(FlatBufferBuilder builder, boolean closeOnEose) { builder.addBoolean(9, closeOnEose, false); }
  public static void addCacheFirst(FlatBufferBuilder builder, boolean cacheFirst) { builder.addBoolean(10, cacheFirst, false); }
  public static void addNoCache(FlatBufferBuilder builder, boolean noCache) { builder.addBoolean(11, noCache, false); }
  public static void addMaxRelays(FlatBufferBuilder builder, int maxRelays) { builder.addShort(12, (short) maxRelays, (short) 0); }
  public static void addCacheOnly(FlatBufferBuilder builder, boolean cacheOnly) { builder.addBoolean(13, cacheOnly, false); }
  public static int endRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Request get(int j) { return get(new Request(), j); }
    public Request get(Request obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

