// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SerializeEventsPipeConfig extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SerializeEventsPipeConfig getRootAsSerializeEventsPipeConfig(ByteBuffer _bb) { return getRootAsSerializeEventsPipeConfig(_bb, new SerializeEventsPipeConfig()); }
  public static SerializeEventsPipeConfig getRootAsSerializeEventsPipeConfig(ByteBuffer _bb, SerializeEventsPipeConfig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SerializeEventsPipeConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String subscriptionId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer subscriptionIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer subscriptionIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createSerializeEventsPipeConfig(FlatBufferBuilder builder,
      int subscriptionIdOffset) {
    builder.startTable(1);
    SerializeEventsPipeConfig.addSubscriptionId(builder, subscriptionIdOffset);
    return SerializeEventsPipeConfig.endSerializeEventsPipeConfig(builder);
  }

  public static void startSerializeEventsPipeConfig(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addSubscriptionId(FlatBufferBuilder builder, int subscriptionIdOffset) { builder.addOffset(0, subscriptionIdOffset, 0); }
  public static int endSerializeEventsPipeConfig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // subscription_id
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SerializeEventsPipeConfig get(int j) { return get(new SerializeEventsPipeConfig(), j); }
    public SerializeEventsPipeConfig get(SerializeEventsPipeConfig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

