// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SetSignerResponse extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SetSignerResponse getRootAsSetSignerResponse(ByteBuffer _bb) { return getRootAsSetSignerResponse(_bb, new SetSignerResponse()); }
  public static SetSignerResponse getRootAsSetSignerResponse(ByteBuffer _bb, SetSignerResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SetSignerResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String pubkey() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String bunkerUrl() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bunkerUrlAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer bunkerUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String error() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer errorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createSetSignerResponse(FlatBufferBuilder builder,
      int pubkeyOffset,
      int bunkerUrlOffset,
      int errorOffset) {
    builder.startTable(3);
    SetSignerResponse.addError(builder, errorOffset);
    SetSignerResponse.addBunkerUrl(builder, bunkerUrlOffset);
    SetSignerResponse.addPubkey(builder, pubkeyOffset);
    return SetSignerResponse.endSetSignerResponse(builder);
  }

  public static void startSetSignerResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(0, pubkeyOffset, 0); }
  public static void addBunkerUrl(FlatBufferBuilder builder, int bunkerUrlOffset) { builder.addOffset(1, bunkerUrlOffset, 0); }
  public static void addError(FlatBufferBuilder builder, int errorOffset) { builder.addOffset(2, errorOffset, 0); }
  public static int endSetSignerResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SetSignerResponse get(int j) { return get(new SetSignerResponse(), j); }
    public SetSignerResponse get(SetSignerResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

