// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SetSigner extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SetSigner getRootAsSetSigner(ByteBuffer _bb) { return getRootAsSetSigner(_bb, new SetSigner()); }
  public static SetSigner getRootAsSetSigner(ByteBuffer _bb, SetSigner obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SetSigner __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte signerTypeType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.google.flatbuffers.Table signerType(com.google.flatbuffers.Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createSetSigner(FlatBufferBuilder builder,
      byte signerTypeType,
      int signerTypeOffset) {
    builder.startTable(2);
    SetSigner.addSignerType(builder, signerTypeOffset);
    SetSigner.addSignerTypeType(builder, signerTypeType);
    return SetSigner.endSetSigner(builder);
  }

  public static void startSetSigner(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addSignerTypeType(FlatBufferBuilder builder, byte signerTypeType) { builder.addByte(0, signerTypeType, 0); }
  public static void addSignerType(FlatBufferBuilder builder, int signerTypeOffset) { builder.addOffset(1, signerTypeOffset, 0); }
  public static int endSetSigner(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // signer_type
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SetSigner get(int j) { return get(new SetSigner(), j); }
    public SetSigner get(SetSigner obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

