// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class SignerOp {
  private SignerOp() { }
  public static final long GetPubkey = 0L;
  public static final long SignEvent = 1L;
  public static final long Nip04Encrypt = 2L;
  public static final long Nip04Decrypt = 3L;
  public static final long Nip44Encrypt = 4L;
  public static final long Nip44Decrypt = 5L;
  public static final long Nip04DecryptBetween = 6L;
  public static final long Nip44DecryptBetween = 7L;
  public static final long VerifyProof = 8L;
  public static final long AuthEvent = 9L;
}

