// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SignedEvent extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SignedEvent getRootAsSignedEvent(ByteBuffer _bb) { return getRootAsSignedEvent(_bb, new SignedEvent()); }
  public static SignedEvent getRootAsSignedEvent(ByteBuffer _bb, SignedEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SignedEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public nostr.fb.NostrEvent event() { return event(new nostr.fb.NostrEvent()); }
  public nostr.fb.NostrEvent event(nostr.fb.NostrEvent obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createSignedEvent(FlatBufferBuilder builder,
      int eventOffset) {
    builder.startTable(1);
    SignedEvent.addEvent(builder, eventOffset);
    return SignedEvent.endSignedEvent(builder);
  }

  public static void startSignedEvent(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addEvent(FlatBufferBuilder builder, int eventOffset) { builder.addOffset(0, eventOffset, 0); }
  public static int endSignedEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // event
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SignedEvent get(int j) { return get(new SignedEvent(), j); }
    public SignedEvent get(SignedEvent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

