// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SignerRequest extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SignerRequest getRootAsSignerRequest(ByteBuffer _bb) { return getRootAsSignerRequest(_bb, new SignerRequest()); }
  public static SignerRequest getRootAsSignerRequest(ByteBuffer _bb, SignerRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SignerRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long requestId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long op() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String payload() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer payloadAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer payloadInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String pubkey() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String senderPubkey() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer senderPubkeyAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer senderPubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String recipientPubkey() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer recipientPubkeyAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer recipientPubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }

  public static int createSignerRequest(FlatBufferBuilder builder,
      long requestId,
      long op,
      int payloadOffset,
      int pubkeyOffset,
      int senderPubkeyOffset,
      int recipientPubkeyOffset) {
    builder.startTable(6);
    SignerRequest.addRequestId(builder, requestId);
    SignerRequest.addRecipientPubkey(builder, recipientPubkeyOffset);
    SignerRequest.addSenderPubkey(builder, senderPubkeyOffset);
    SignerRequest.addPubkey(builder, pubkeyOffset);
    SignerRequest.addPayload(builder, payloadOffset);
    SignerRequest.addOp(builder, op);
    return SignerRequest.endSignerRequest(builder);
  }

  public static void startSignerRequest(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addRequestId(FlatBufferBuilder builder, long requestId) { builder.addLong(0, requestId, 0L); }
  public static void addOp(FlatBufferBuilder builder, long op) { builder.addInt(1, (int) op, (int) 0L); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(2, payloadOffset, 0); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(3, pubkeyOffset, 0); }
  public static void addSenderPubkey(FlatBufferBuilder builder, int senderPubkeyOffset) { builder.addOffset(4, senderPubkeyOffset, 0); }
  public static void addRecipientPubkey(FlatBufferBuilder builder, int recipientPubkeyOffset) { builder.addOffset(5, recipientPubkeyOffset, 0); }
  public static int endSignerRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SignerRequest get(int j) { return get(new SignerRequest(), j); }
    public SignerRequest get(SignerRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

