// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SignEvent extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SignEvent getRootAsSignEvent(ByteBuffer _bb) { return getRootAsSignEvent(_bb, new SignEvent()); }
  public static SignEvent getRootAsSignEvent(ByteBuffer _bb, SignEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SignEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public nostr.fb.Template template() { return template(new nostr.fb.Template()); }
  public nostr.fb.Template template(nostr.fb.Template obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createSignEvent(FlatBufferBuilder builder,
      int templateOffset) {
    builder.startTable(1);
    SignEvent.addTemplate(builder, templateOffset);
    return SignEvent.endSignEvent(builder);
  }

  public static void startSignEvent(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addTemplate(FlatBufferBuilder builder, int templateOffset) { builder.addOffset(0, templateOffset, 0); }
  public static int endSignEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // template
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SignEvent get(int j) { return get(new SignEvent(), j); }
    public SignEvent get(SignEvent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

