// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class SignerType {
  private SignerType() { }
  public static final byte NONE = 0;
  public static final byte PrivateKey = 1;
  public static final byte Nip07 = 2;
  public static final byte Nip46Bunker = 3;
  public static final byte Nip46QR = 4;

  public static final String[] names = { "NONE", "PrivateKey", "Nip07", "Nip46Bunker", "Nip46QR", };

  public static String name(int e) { return names[e]; }
}

