// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SignerResponse extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SignerResponse getRootAsSignerResponse(ByteBuffer _bb) { return getRootAsSignerResponse(_bb, new SignerResponse()); }
  public static SignerResponse getRootAsSignerResponse(ByteBuffer _bb, SignerResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SignerResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long requestId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String result() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer resultAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer resultInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String error() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer errorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createSignerResponse(FlatBufferBuilder builder,
      long requestId,
      int resultOffset,
      int errorOffset) {
    builder.startTable(3);
    SignerResponse.addRequestId(builder, requestId);
    SignerResponse.addError(builder, errorOffset);
    SignerResponse.addResult(builder, resultOffset);
    return SignerResponse.endSignerResponse(builder);
  }

  public static void startSignerResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addRequestId(FlatBufferBuilder builder, long requestId) { builder.addLong(0, requestId, 0L); }
  public static void addResult(FlatBufferBuilder builder, int resultOffset) { builder.addOffset(1, resultOffset, 0); }
  public static void addError(FlatBufferBuilder builder, int errorOffset) { builder.addOffset(2, errorOffset, 0); }
  public static int endSignerResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SignerResponse get(int j) { return get(new SignerResponse(), j); }
    public SignerResponse get(SignerResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

