// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Subscribe extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Subscribe getRootAsSubscribe(ByteBuffer _bb) { return getRootAsSubscribe(_bb, new Subscribe()); }
  public static Subscribe getRootAsSubscribe(ByteBuffer _bb, Subscribe obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Subscribe __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String subscriptionId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer subscriptionIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer subscriptionIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public nostr.fb.Request requests(int j) { return requests(new nostr.fb.Request(), j); }
  public nostr.fb.Request requests(nostr.fb.Request obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int requestsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.Request.Vector requestsVector() { return requestsVector(new nostr.fb.Request.Vector()); }
  public nostr.fb.Request.Vector requestsVector(nostr.fb.Request.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public nostr.fb.SubscriptionConfig config() { return config(new nostr.fb.SubscriptionConfig()); }
  public nostr.fb.SubscriptionConfig config(nostr.fb.SubscriptionConfig obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createSubscribe(FlatBufferBuilder builder,
      int subscriptionIdOffset,
      int requestsOffset,
      int configOffset) {
    builder.startTable(3);
    Subscribe.addConfig(builder, configOffset);
    Subscribe.addRequests(builder, requestsOffset);
    Subscribe.addSubscriptionId(builder, subscriptionIdOffset);
    return Subscribe.endSubscribe(builder);
  }

  public static void startSubscribe(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addSubscriptionId(FlatBufferBuilder builder, int subscriptionIdOffset) { builder.addOffset(0, subscriptionIdOffset, 0); }
  public static void addRequests(FlatBufferBuilder builder, int requestsOffset) { builder.addOffset(1, requestsOffset, 0); }
  public static int createRequestsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRequestsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addConfig(FlatBufferBuilder builder, int configOffset) { builder.addOffset(2, configOffset, 0); }
  public static int endSubscribe(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // subscription_id
    builder.required(o, 6);  // requests
    builder.required(o, 8);  // config
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Subscribe get(int j) { return get(new Subscribe(), j); }
    public Subscribe get(Subscribe obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

