// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class SubscribeKind {
  private SubscribeKind() { }
  public static final byte CachedEvent = 0;
  public static final byte FetchedEvent = 1;
  public static final byte Count = 2;
  public static final byte ConnectionStatus = 3;
  public static final byte Eoce = 4;
  public static final byte BufferFull = 5;

  public static final String[] names = { "CachedEvent", "FetchedEvent", "Count", "ConnectionStatus", "Eoce", "BufferFull", };

  public static String name(int e) { return names[e]; }
}

