// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ValidProofs extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ValidProofs getRootAsValidProofs(ByteBuffer _bb) { return getRootAsValidProofs(_bb, new ValidProofs()); }
  public static ValidProofs getRootAsValidProofs(ByteBuffer _bb, ValidProofs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ValidProofs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public nostr.fb.MintProofs proofs(int j) { return proofs(new nostr.fb.MintProofs(), j); }
  public nostr.fb.MintProofs proofs(nostr.fb.MintProofs obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int proofsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.MintProofs.Vector proofsVector() { return proofsVector(new nostr.fb.MintProofs.Vector()); }
  public nostr.fb.MintProofs.Vector proofsVector(nostr.fb.MintProofs.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createValidProofs(FlatBufferBuilder builder,
      int proofsOffset) {
    builder.startTable(1);
    ValidProofs.addProofs(builder, proofsOffset);
    return ValidProofs.endValidProofs(builder);
  }

  public static void startValidProofs(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addProofs(FlatBufferBuilder builder, int proofsOffset) { builder.addOffset(0, proofsOffset, 0); }
  public static int createProofsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startProofsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endValidProofs(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // proofs
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ValidProofs get(int j) { return get(new ValidProofs(), j); }
    public ValidProofs get(ValidProofs obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

