// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class VideoData extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static VideoData getRootAsVideoData(ByteBuffer _bb) { return getRootAsVideoData(_bb, new VideoData()); }
  public static VideoData getRootAsVideoData(ByteBuffer _bb, VideoData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VideoData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String url() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String thumbnail() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer thumbnailAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer thumbnailInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String dim() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dimAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer dimInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createVideoData(FlatBufferBuilder builder,
      int urlOffset,
      int thumbnailOffset,
      int dimOffset) {
    builder.startTable(3);
    VideoData.addDim(builder, dimOffset);
    VideoData.addThumbnail(builder, thumbnailOffset);
    VideoData.addUrl(builder, urlOffset);
    return VideoData.endVideoData(builder);
  }

  public static void startVideoData(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(0, urlOffset, 0); }
  public static void addThumbnail(FlatBufferBuilder builder, int thumbnailOffset) { builder.addOffset(1, thumbnailOffset, 0); }
  public static void addDim(FlatBufferBuilder builder, int dimOffset) { builder.addOffset(2, dimOffset, 0); }
  public static int endVideoData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // url
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VideoData get(int j) { return get(new VideoData(), j); }
    public VideoData get(VideoData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

