// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class VideoVariant extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static VideoVariant getRootAsVideoVariant(ByteBuffer _bb) { return getRootAsVideoVariant(_bb, new VideoVariant()); }
  public static VideoVariant getRootAsVideoVariant(ByteBuffer _bb, VideoVariant obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VideoVariant __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String url() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String mimeType() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mimeTypeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer mimeTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String dim() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dimAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer dimInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String blurhash() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer blurhashAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer blurhashInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String hash() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hashAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer hashInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public float duration() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public long bitrate() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String image() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer imageAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer imageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public String fallback(int j) { int o = __offset(20); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int fallbackLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public StringVector fallbackVector() { return fallbackVector(new StringVector()); }
  public StringVector fallbackVector(StringVector obj) { int o = __offset(20); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createVideoVariant(FlatBufferBuilder builder,
      int urlOffset,
      int mimeTypeOffset,
      int dimOffset,
      int blurhashOffset,
      int hashOffset,
      float duration,
      long bitrate,
      int imageOffset,
      int fallbackOffset) {
    builder.startTable(9);
    VideoVariant.addBitrate(builder, bitrate);
    VideoVariant.addFallback(builder, fallbackOffset);
    VideoVariant.addImage(builder, imageOffset);
    VideoVariant.addDuration(builder, duration);
    VideoVariant.addHash(builder, hashOffset);
    VideoVariant.addBlurhash(builder, blurhashOffset);
    VideoVariant.addDim(builder, dimOffset);
    VideoVariant.addMimeType(builder, mimeTypeOffset);
    VideoVariant.addUrl(builder, urlOffset);
    return VideoVariant.endVideoVariant(builder);
  }

  public static void startVideoVariant(FlatBufferBuilder builder) { builder.startTable(9); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(0, urlOffset, 0); }
  public static void addMimeType(FlatBufferBuilder builder, int mimeTypeOffset) { builder.addOffset(1, mimeTypeOffset, 0); }
  public static void addDim(FlatBufferBuilder builder, int dimOffset) { builder.addOffset(2, dimOffset, 0); }
  public static void addBlurhash(FlatBufferBuilder builder, int blurhashOffset) { builder.addOffset(3, blurhashOffset, 0); }
  public static void addHash(FlatBufferBuilder builder, int hashOffset) { builder.addOffset(4, hashOffset, 0); }
  public static void addDuration(FlatBufferBuilder builder, float duration) { builder.addFloat(5, duration, 0.0f); }
  public static void addBitrate(FlatBufferBuilder builder, long bitrate) { builder.addLong(6, bitrate, 0L); }
  public static void addImage(FlatBufferBuilder builder, int imageOffset) { builder.addOffset(7, imageOffset, 0); }
  public static void addFallback(FlatBufferBuilder builder, int fallbackOffset) { builder.addOffset(8, fallbackOffset, 0); }
  public static int createFallbackVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFallbackVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endVideoVariant(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // url
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VideoVariant get(int j) { return get(new VideoVariant(), j); }
    public VideoVariant get(VideoVariant obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

