// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

@SuppressWarnings("unused")
public final class Witness {
  private Witness() { }
  public static final byte NONE = 0;
  public static final byte WitnessString = 1;
  public static final byte P2PKWitness = 2;
  public static final byte HTLCWitness = 3;

  public static final String[] names = { "NONE", "WitnessString", "P2PKWitness", "HTLCWitness", };

  public static String name(int e) { return names[e]; }
}

