// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class WorkerMessage extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static WorkerMessage getRootAsWorkerMessage(ByteBuffer _bb) { return getRootAsWorkerMessage(_bb, new WorkerMessage()); }
  public static WorkerMessage getRootAsWorkerMessage(ByteBuffer _bb, WorkerMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public WorkerMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String subId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer subIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer subIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String url() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long type() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public byte contentType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.google.flatbuffers.Table content(com.google.flatbuffers.Table obj) { int o = __offset(12); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createWorkerMessage(FlatBufferBuilder builder,
      int subIdOffset,
      int urlOffset,
      long type,
      byte contentType,
      int contentOffset) {
    builder.startTable(5);
    WorkerMessage.addContent(builder, contentOffset);
    WorkerMessage.addType(builder, type);
    WorkerMessage.addUrl(builder, urlOffset);
    WorkerMessage.addSubId(builder, subIdOffset);
    WorkerMessage.addContentType(builder, contentType);
    return WorkerMessage.endWorkerMessage(builder);
  }

  public static void startWorkerMessage(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addSubId(FlatBufferBuilder builder, int subIdOffset) { builder.addOffset(0, subIdOffset, 0); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(1, urlOffset, 0); }
  public static void addType(FlatBufferBuilder builder, long type) { builder.addInt(2, (int) type, (int) 0L); }
  public static void addContentType(FlatBufferBuilder builder, byte contentType) { builder.addByte(3, contentType, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(4, contentOffset, 0); }
  public static int endWorkerMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishWorkerMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedWorkerMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public WorkerMessage get(int j) { return get(new WorkerMessage(), j); }
    public WorkerMessage get(WorkerMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

