// automatically generated by the FlatBuffers compiler, do not modify

package nostr.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ZapRequest extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ZapRequest getRootAsZapRequest(ByteBuffer _bb) { return getRootAsZapRequest(_bb, new ZapRequest()); }
  public static ZapRequest getRootAsZapRequest(ByteBuffer _bb, ZapRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ZapRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int kind() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public String pubkey() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pubkeyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer pubkeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String content() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public nostr.fb.StringVec tags(int j) { return tags(new nostr.fb.StringVec(), j); }
  public nostr.fb.StringVec tags(nostr.fb.StringVec obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int tagsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public nostr.fb.StringVec.Vector tagsVector() { return tagsVector(new nostr.fb.StringVec.Vector()); }
  public nostr.fb.StringVec.Vector tagsVector(nostr.fb.StringVec.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String signature() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer signatureAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer signatureInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }

  public static int createZapRequest(FlatBufferBuilder builder,
      int kind,
      int pubkeyOffset,
      int contentOffset,
      int tagsOffset,
      int signatureOffset) {
    builder.startTable(5);
    ZapRequest.addSignature(builder, signatureOffset);
    ZapRequest.addTags(builder, tagsOffset);
    ZapRequest.addContent(builder, contentOffset);
    ZapRequest.addPubkey(builder, pubkeyOffset);
    ZapRequest.addKind(builder, kind);
    return ZapRequest.endZapRequest(builder);
  }

  public static void startZapRequest(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addKind(FlatBufferBuilder builder, int kind) { builder.addShort(0, (short) kind, (short) 0); }
  public static void addPubkey(FlatBufferBuilder builder, int pubkeyOffset) { builder.addOffset(1, pubkeyOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(2, contentOffset, 0); }
  public static void addTags(FlatBufferBuilder builder, int tagsOffset) { builder.addOffset(3, tagsOffset, 0); }
  public static int createTagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSignature(FlatBufferBuilder builder, int signatureOffset) { builder.addOffset(4, signatureOffset, 0); }
  public static int endZapRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // pubkey
    builder.required(o, 8);  // content
    builder.required(o, 10);  // tags
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ZapRequest get(int j) { return get(new ZapRequest(), j); }
    public ZapRequest get(ZapRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

