{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.99.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.11.aar",
          "url": "nipworker-native-ffi-android-0.99.11.aar",
          "size": 34451360,
          "sha512": "17645aacc2072e64681b6f32b4f168a2380fc57149411f4f9a3525b04929273da688370a3774b140843317aacdeef0bd1895dcbea351c27917293ae98b92f433",
          "sha256": "6e727b3c83f711c05887a0ea49bc64f4c8d5754ebae8a8b107bebdc36357e98c",
          "sha1": "53c2d26d58456ec1907eb199c42d12afaec5f687",
          "md5": "82e995dfed71f7c6bb63e65788d5e872"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.11.aar",
          "url": "nipworker-native-ffi-android-0.99.11.aar",
          "size": 34451360,
          "sha512": "17645aacc2072e64681b6f32b4f168a2380fc57149411f4f9a3525b04929273da688370a3774b140843317aacdeef0bd1895dcbea351c27917293ae98b92f433",
          "sha256": "6e727b3c83f711c05887a0ea49bc64f4c8d5754ebae8a8b107bebdc36357e98c",
          "sha1": "53c2d26d58456ec1907eb199c42d12afaec5f687",
          "md5": "82e995dfed71f7c6bb63e65788d5e872"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.11-sources.jar",
          "url": "nipworker-native-ffi-android-0.99.11-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
