{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.99.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.5.aar",
          "url": "nipworker-native-ffi-android-0.99.5.aar",
          "size": 34424645,
          "sha512": "74885d651cb7c7ab5906be30cf8ed7689923b5b3052660d75d85e6cb3252a05d79170bd48e57701c9091d33e9d1b6e49bb45ea707ce0d33c7d5ffa5c422258de",
          "sha256": "9027286bf47af04ddb3b1d30c66e72650ffaa1778e736d08f73c1cd0b1713302",
          "sha1": "55698cc51208f2aa48d96ed267299eea9c3c47d9",
          "md5": "46255f40423417aca2b59592d85f5213"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.5.aar",
          "url": "nipworker-native-ffi-android-0.99.5.aar",
          "size": 34424645,
          "sha512": "74885d651cb7c7ab5906be30cf8ed7689923b5b3052660d75d85e6cb3252a05d79170bd48e57701c9091d33e9d1b6e49bb45ea707ce0d33c7d5ffa5c422258de",
          "sha256": "9027286bf47af04ddb3b1d30c66e72650ffaa1778e736d08f73c1cd0b1713302",
          "sha1": "55698cc51208f2aa48d96ed267299eea9c3c47d9",
          "md5": "46255f40423417aca2b59592d85f5213"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.5-sources.jar",
          "url": "nipworker-native-ffi-android-0.99.5-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
