{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.97.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.6.aar",
          "url": "nipworker-native-ffi-android-0.97.6.aar",
          "size": 33860198,
          "sha512": "5a9ab5dea6ada5c47e550091e6b52166753f19a7d24c486b239aecc256b40aa8ae5906b399921f85b4706691cf4e6ae3cc5c95df3a257f9e8f60db8237022076",
          "sha256": "57e0c8215798d29efa689829f049fd9ed14a66e8f646d1db02383d302c98df97",
          "sha1": "743ffe5f257e964e532ad71998b95be7fb3db0e0",
          "md5": "bcb90b551b43bcc54c282a0ce3190bf1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.6.aar",
          "url": "nipworker-native-ffi-android-0.97.6.aar",
          "size": 33860198,
          "sha512": "5a9ab5dea6ada5c47e550091e6b52166753f19a7d24c486b239aecc256b40aa8ae5906b399921f85b4706691cf4e6ae3cc5c95df3a257f9e8f60db8237022076",
          "sha256": "57e0c8215798d29efa689829f049fd9ed14a66e8f646d1db02383d302c98df97",
          "sha1": "743ffe5f257e964e532ad71998b95be7fb3db0e0",
          "md5": "bcb90b551b43bcc54c282a0ce3190bf1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.6-sources.jar",
          "url": "nipworker-native-ffi-android-0.97.6-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
