/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_eose_free: (a: number, b: number) => void;
export const __wbg_get_eose_total_connections: (a: number) => number;
export const __wbg_set_eose_total_connections: (a: number, b: number) => void;
export const __wbg_get_eose_remaining_connections: (a: number) => number;
export const __wbg_set_eose_remaining_connections: (a: number, b: number) => void;
export const eose_new: (a: number, b: number) => number;
export const eose_is_complete: (a: number) => number;
export const eose_completed_connections: (a: number) => number;
export const eose_completion_percentage: (a: number) => number;
export const eose_to_json: (a: number, b: number) => void;
export const eose_from_json: (a: number, b: number, c: number) => void;
export const __wbg_nostrclient_free: (a: number, b: number) => void;
export const nostrclient_new: () => number;
export const nostrclient_open_subscription: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const nostrclient_close_subscription: (a: number, b: number, c: number) => number;
export const nostrclient_set_signer: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const nostrclient_get_public_key: (a: number, b: number) => void;
export const nostrclient_get_active_subscription_count: (a: number) => number;
export const nostrclient_get_connection_count: (a: number) => number;
export const nostrclient_handle_message: (a: number, b: number) => number;
export const init_nostr_client: () => number;
export const rustsecp256k1_v0_8_1_context_create: (a: number) => number;
export const rustsecp256k1_v0_8_1_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_8_1_default_illegal_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_8_1_default_error_callback_fn: (a: number, b: number) => void;
export const __wbindgen_export_0: (a: number) => void;
export const __wbindgen_export_1: (a: number, b: number, c: number) => void;
export const __wbindgen_export_2: (a: number, b: number) => number;
export const __wbindgen_export_3: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export_5: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: (a: number, b: number) => void;
export const __wbindgen_export_7: (a: number, b: number, c: number) => void;
export const __wbindgen_export_8: (a: number, b: number, c: number) => void;
export const __wbindgen_export_9: (a: number, b: number, c: number) => void;
export const __wbindgen_export_10: (a: number, b: number) => void;
export const __wbindgen_export_11: (a: number, b: number, c: number, d: number) => void;
