[package]
name = "ws-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
js-sys = "0.3.70"
web-sys = { version = "0.3.70", features = ["console", "Window"] }

# WebSocket client and timers for wasm
gloo-net = { version = "0.5", features = ["websocket"] }
gloo-timers = { version = "0.2", features = ["futures"] }

# Async utilities
futures = "0.3"

# JSON (for envelope parsing in the inRing reader)
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Lightweight logging macros used in code
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
thiserror = "1.0"

[dev-dependencies]
wasm-bindgen-test = "0.3"


[package.metadata.wasm-pack.profile.release]
wasm-opt = [
    "-O",
    "--strip-debug",
    "--strip-producers",
    "--enable-bulk-memory",
    "--enable-sign-ext",
    "--enable-mutable-globals",
    "--enable-nontrapping-float-to-int",
]
