{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.98.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.98.0.aar",
          "url": "nipworker-native-ffi-android-0.98.0.aar",
          "size": 34317354,
          "sha512": "fbe414e9910e6bdcf8d60a30ac6c4735da37e2bb8e618b08eee8b57547256ab3972dee8b4332db255b0fc8d5e9b05980d73cb22850ae392568f72382df23cf0c",
          "sha256": "93acae2a2ba30040feee39bd85575ba65b65fe9d1cd7b3267a1f270c68932b8e",
          "sha1": "82d3eeb33545e7737f4af761efe9d271598567a1",
          "md5": "72697a77da43f1ac570feefb8ec49470"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.98.0.aar",
          "url": "nipworker-native-ffi-android-0.98.0.aar",
          "size": 34317354,
          "sha512": "fbe414e9910e6bdcf8d60a30ac6c4735da37e2bb8e618b08eee8b57547256ab3972dee8b4332db255b0fc8d5e9b05980d73cb22850ae392568f72382df23cf0c",
          "sha256": "93acae2a2ba30040feee39bd85575ba65b65fe9d1cd7b3267a1f270c68932b8e",
          "sha1": "82d3eeb33545e7737f4af761efe9d271598567a1",
          "md5": "72697a77da43f1ac570feefb8ec49470"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.98.0-sources.jar",
          "url": "nipworker-native-ffi-android-0.98.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
