{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.99.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.13.aar",
          "url": "nipworker-native-ffi-android-0.99.13.aar",
          "size": 34511508,
          "sha512": "a980c4d8fe127335a5bb9158ddec7c10eadf8e36ab21bddd9a09a210edae536b34a8ebe1f094dc4cc88c88b3da5ec2ec536a3f7c4ec6f56836e96b1e7f56e7a8",
          "sha256": "1f929d85c2272a8d9e673c8210f8953682ed08258cc488c36014498ad51cab61",
          "sha1": "07962b74ea549b604f5b7e64a1fc6dc1bff0294e",
          "md5": "859b4e0102ecd48fb69f93c452f0bff5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.13.aar",
          "url": "nipworker-native-ffi-android-0.99.13.aar",
          "size": 34511508,
          "sha512": "a980c4d8fe127335a5bb9158ddec7c10eadf8e36ab21bddd9a09a210edae536b34a8ebe1f094dc4cc88c88b3da5ec2ec536a3f7c4ec6f56836e96b1e7f56e7a8",
          "sha256": "1f929d85c2272a8d9e673c8210f8953682ed08258cc488c36014498ad51cab61",
          "sha1": "07962b74ea549b604f5b7e64a1fc6dc1bff0294e",
          "md5": "859b4e0102ecd48fb69f93c452f0bff5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.13-sources.jar",
          "url": "nipworker-native-ffi-android-0.99.13-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
