{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.98.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.98.1.aar",
          "url": "nipworker-native-ffi-android-0.98.1.aar",
          "size": 34357708,
          "sha512": "2eb7f36ae55e7abd083fec767b41cf7444b5a7d319246fede876ee42153d976a1e2ed6ba2952b1e872f1559f704770a9c0dade188c3e25ccb67b44fe79a2084b",
          "sha256": "8bdbf40983a973a8bc3ab09e0e9b75602d1a319a614388139a460e3057bb6e47",
          "sha1": "aadc56f9bb469593e79427414d7f88796eada1f8",
          "md5": "283bfc87dd312ab850d0e9ece5944cff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.98.1.aar",
          "url": "nipworker-native-ffi-android-0.98.1.aar",
          "size": 34357708,
          "sha512": "2eb7f36ae55e7abd083fec767b41cf7444b5a7d319246fede876ee42153d976a1e2ed6ba2952b1e872f1559f704770a9c0dade188c3e25ccb67b44fe79a2084b",
          "sha256": "8bdbf40983a973a8bc3ab09e0e9b75602d1a319a614388139a460e3057bb6e47",
          "sha1": "aadc56f9bb469593e79427414d7f88796eada1f8",
          "md5": "283bfc87dd312ab850d0e9ece5944cff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.98.1-sources.jar",
          "url": "nipworker-native-ffi-android-0.98.1-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
