{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.99.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.7.aar",
          "url": "nipworker-native-ffi-android-0.99.7.aar",
          "size": 34422783,
          "sha512": "496b3f98d24d7fc54a5e71910a30b5b0f2b4a0ae3e11acecffe2bbd88b03a71891f561f715cc5185a257a2a60b07506b27fcf2d4f701b1d99ec6de132f19bd1b",
          "sha256": "28b182917bde8ceccea160f3477e0d3e18086fccd961543ae6bcca6e241d04d6",
          "sha1": "4edfdd83447c60a27fb4f3a01604af3261ff6f7e",
          "md5": "a51719c309b14ae7959550c405a32564"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.7.aar",
          "url": "nipworker-native-ffi-android-0.99.7.aar",
          "size": 34422783,
          "sha512": "496b3f98d24d7fc54a5e71910a30b5b0f2b4a0ae3e11acecffe2bbd88b03a71891f561f715cc5185a257a2a60b07506b27fcf2d4f701b1d99ec6de132f19bd1b",
          "sha256": "28b182917bde8ceccea160f3477e0d3e18086fccd961543ae6bcca6e241d04d6",
          "sha1": "4edfdd83447c60a27fb4f3a01604af3261ff6f7e",
          "md5": "a51719c309b14ae7959550c405a32564"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.7-sources.jar",
          "url": "nipworker-native-ffi-android-0.99.7-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
