{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.97.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.3.aar",
          "url": "nipworker-native-ffi-android-0.97.3.aar",
          "size": 33785682,
          "sha512": "3fd59833c2572946dbb022f693fb30089fb3a9c9db52117ddad32018b77383b3dc3a3a2619143913c1e2c08d378a20aa71dc9f216f16f055c02646641fecd05c",
          "sha256": "7e10f38a70a7ca0a63bb6029501f69f5bc2adff2623d086cf5c931d56d65bc94",
          "sha1": "cdc1b513fb16c5cc4f5f060ffdc0696918bf76c7",
          "md5": "02ce4c18a099248c1ffda0e0188808ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.3.aar",
          "url": "nipworker-native-ffi-android-0.97.3.aar",
          "size": 33785682,
          "sha512": "3fd59833c2572946dbb022f693fb30089fb3a9c9db52117ddad32018b77383b3dc3a3a2619143913c1e2c08d378a20aa71dc9f216f16f055c02646641fecd05c",
          "sha256": "7e10f38a70a7ca0a63bb6029501f69f5bc2adff2623d086cf5c931d56d65bc94",
          "sha1": "cdc1b513fb16c5cc4f5f060ffdc0696918bf76c7",
          "md5": "02ce4c18a099248c1ffda0e0188808ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.3-sources.jar",
          "url": "nipworker-native-ffi-android-0.97.3-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
