{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.97.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.3.aar",
          "url": "nipworker-native-ffi-android-0.97.3.aar",
          "size": 33786034,
          "sha512": "657d0538708c28c03f1fabba1aa0fed50011e3bd599fa786a6f894fdf9bd1bdfcc43b8c39d0fdd692354a630659e2e8a292b4b21de5d779f6b0d8dfa46ff79c2",
          "sha256": "5b005c0350a9dd978bbd9100d6d55bb9edc3a2e5cdb0a4a95b4d46cc6ece5472",
          "sha1": "5a552feaf42d9451142fcdbf31f8d81e966e5a80",
          "md5": "4b7198a7e6dd59d0032df725bd3e5cfd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.3.aar",
          "url": "nipworker-native-ffi-android-0.97.3.aar",
          "size": 33786034,
          "sha512": "657d0538708c28c03f1fabba1aa0fed50011e3bd599fa786a6f894fdf9bd1bdfcc43b8c39d0fdd692354a630659e2e8a292b4b21de5d779f6b0d8dfa46ff79c2",
          "sha256": "5b005c0350a9dd978bbd9100d6d55bb9edc3a2e5cdb0a4a95b4d46cc6ece5472",
          "sha1": "5a552feaf42d9451142fcdbf31f8d81e966e5a80",
          "md5": "4b7198a7e6dd59d0032df725bd3e5cfd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.3-sources.jar",
          "url": "nipworker-native-ffi-android-0.97.3-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
