{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.97.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.8.aar",
          "url": "nipworker-native-ffi-android-0.97.8.aar",
          "size": 34338522,
          "sha512": "0caf4c76f573bf3b835c0634fdb2435296794f553b3f6f2b493e942395f1182ceac58c2bc2962a848aeebb36a0332e864847ef9e960e6a882b6071ef324d0aa8",
          "sha256": "c7410c747d7786ebf631e076f766e42b7d3d4f5211adc08ebc08467d28231d1d",
          "sha1": "fed23a645d81f24bffdfd0cf637e1054282f831c",
          "md5": "08dcbb86317ef7360d2bbc32b505270e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.8.aar",
          "url": "nipworker-native-ffi-android-0.97.8.aar",
          "size": 34338522,
          "sha512": "0caf4c76f573bf3b835c0634fdb2435296794f553b3f6f2b493e942395f1182ceac58c2bc2962a848aeebb36a0332e864847ef9e960e6a882b6071ef324d0aa8",
          "sha256": "c7410c747d7786ebf631e076f766e42b7d3d4f5211adc08ebc08467d28231d1d",
          "sha1": "fed23a645d81f24bffdfd0cf637e1054282f831c",
          "md5": "08dcbb86317ef7360d2bbc32b505270e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.97.8-sources.jar",
          "url": "nipworker-native-ffi-android-0.97.8-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
