{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candypoets",
    "module": "nipworker-native-ffi-android",
    "version": "0.99.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.6.aar",
          "url": "nipworker-native-ffi-android-0.99.6.aar",
          "size": 34426171,
          "sha512": "660bce127e9227e3d2bea11d7523330d970afd3d5ec82cfded01c6291812b604df9a902424dd51e4c0903dda8bbd79c0490186fe1f309e10ddcd7df1016f1616",
          "sha256": "69370b8536f34c534b929bbb202e5f9386248ce12136a37a3141795ba1692730",
          "sha1": "15f8969512485850a04a72994ef376c4ae75a65b",
          "md5": "82d9e253287822272b26bf60fb8ccdd3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.6.aar",
          "url": "nipworker-native-ffi-android-0.99.6.aar",
          "size": 34426171,
          "sha512": "660bce127e9227e3d2bea11d7523330d970afd3d5ec82cfded01c6291812b604df9a902424dd51e4c0903dda8bbd79c0490186fe1f309e10ddcd7df1016f1616",
          "sha256": "69370b8536f34c534b929bbb202e5f9386248ce12136a37a3141795ba1692730",
          "sha1": "15f8969512485850a04a72994ef376c4ae75a65b",
          "md5": "82d9e253287822272b26bf60fb8ccdd3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nipworker-native-ffi-android-0.99.6-sources.jar",
          "url": "nipworker-native-ffi-android-0.99.6-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
